// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1WO7-4kZmYUk1-BOuBF_0wVzYpww7UY',
    appId: '1:427705694089:web:8ac5ce6e2c5e0bf4fdd358',
    messagingSenderId: '427705694089',
    projectId: 'toeic-app-6d983',
    authDomain: 'toeic-app-6d983.firebaseapp.com',
    storageBucket: 'toeic-app-6d983.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdTDxR3WQNPsG4xhoMP55CVA_BQVy2fac',
    appId: '1:427705694089:android:cb7c769378a6e083fdd358',
    messagingSenderId: '427705694089',
    projectId: 'toeic-app-6d983',
    storageBucket: 'toeic-app-6d983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_GQdPzzjMCDV9gSpTjwRxoomlbK_qfGk',
    appId: '1:427705694089:ios:80a1f7fe97219181fdd358',
    messagingSenderId: '427705694089',
    projectId: 'toeic-app-6d983',
    storageBucket: 'toeic-app-6d983.firebasestorage.app',
    iosBundleId: 'com.example.toeicApp',
  );

}