import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedVocabMedium() async {
  final db = FirebaseFirestore.instance;
  const levelId = 'medium';

  // Helper: chuyển "Put on" -> "put_on.mp3"
  String _toFileName(String word) {
    final lower = word.toLowerCase();
    final snake = lower
        .replaceAll(
          RegExp(r'[^a-z0-9]+'),
          '_',
        ) // mọi ký tự không phải a-z0-9 -> _
        .replaceAll(RegExp(r'_+'), '_') // gộp nhiều _ liên tiếp
        .replaceAll(RegExp(r'^_+|_+$'), ''); // bỏ _ ở đầu/cuối
    return '$snake.mp3';
  }

  Future<void> _seedTopic({
    required String topicId,
    required String topicName,
    required List<Map<String, String>> cards,
  }) async {
    await db
        .collection('vocab_cards')
        .doc(levelId)
        .collection('vocab_topics')
        .doc(topicId)
        .set({
          'topicName': topicName,
          'createdAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));

    for (int i = 1; i < cards.length; i++) {
      final id = 'q${i.toString().padLeft(2, '0')}';
      final q = cards[i - 1];

      final word = (q['word'] as String);
      final audioUrl =
          'medium/${topicId}/${_toFileName(word)}'; // ví dụ: "put_on.mp3"

      await db
          .collection('vocab_cards')
          .doc(levelId)
          .collection('vocab_topics')
          .doc(topicId)
          .collection('cards')
          .doc(id)
          .set({
            'word': q['word'],
            'phonetic': q['phonetic'],
            'meaningVi': q['meaningVi'],
            'exampleEn': q['exampleEn'],
            'exampleVi': q['exampleVi'],
            'audioUrl': audioUrl,
          }, SetOptions(merge: true));
    }
  }

  // Root doc
  await db.collection('vocab_cards').doc(levelId).set({
    'title': 'Vocabulary Level Medium',
    'vocabTopicId': [
      'vocab1',
      'vocab2',
      'vocab3',
      'vocab4',
      'vocab5',
      'vocab6',
      'vocab7',
      'vocab8',
      'vocab9',
      'vocab10',
    ],
    'createdAt': FieldValue.serverTimestamp(),
  }, SetOptions(merge: true));

  // =========================================================
  // Vocab 1: Meetings & Project Workflow (30 thẻ)
  // Nguồn: vocab1.pdf
  // =========================================================
  final vocab1 = <Map<String, String>>[
    {
      'word': 'agenda',
      'phonetic': '/əˈdʒendə/',
      'meaningVi': 'chương trình họp',
      'exampleEn': 'What’s on the agenda today?',
      'exampleVi': 'Hôm nay chương trình họp có gì?',
    },
    {
      'word': 'minutes',
      'phonetic': '/ˈmɪnɪts/',
      'meaningVi': 'biên bản họp',
      'exampleEn': 'She took the minutes.',
      'exampleVi': 'Cô ấy ghi biên bản họp.',
    },
    {
      'word': 'deadline',
      'phonetic': '/ˈdedlaɪn/',
      'meaningVi': 'hạn chót',
      'exampleEn': 'The deadline is Tuesday.',
      'exampleVi': 'Hạn chót là thứ Ba.',
    },
    {
      'word': 'assign',
      'phonetic': '/əˈsaɪn/',
      'meaningVi': 'phân công',
      'exampleEn': 'The manager assigned tasks.',
      'exampleVi': 'Quản lý đã phân công nhiệm vụ.',
    },
    {
      'word': 'delegate',
      'phonetic': '/ˈdelɪɡeɪt/',
      'meaningVi': 'ủy quyền, giao việc',
      'exampleEn': 'Please delegate minor tasks.',
      'exampleVi': 'Hãy giao các việc nhỏ.',
    },
    {
      'word': 'brainstorm',
      'phonetic': '/ˈbreɪnstɔːrm/',
      'meaningVi': 'động não',
      'exampleEn': 'Let’s brainstorm ideas.',
      'exampleVi': 'Hãy động não ý tưởng.',
    },
    {
      'word': 'milestone',
      'phonetic': '/ˈmaɪlstoʊn/',
      'meaningVi': 'cột mốc',
      'exampleEn': 'We reached the first milestone.',
      'exampleVi': 'Ta đã đạt cột mốc đầu.',
    },
    {
      'word': 'timeline',
      'phonetic': '/ˈtaɪmlaɪn/',
      'meaningVi': 'tiến độ thời gian',
      'exampleEn': 'Share the project timeline.',
      'exampleVi': 'Chia sẻ tiến độ dự án.',
    },
    {
      'word': 'kickoff',
      'phonetic': '/ˈkɪkˌɔːf/',
      'meaningVi': 'buổi khởi động',
      'exampleEn': 'The kickoff is on Monday.',
      'exampleVi': 'Buổi khởi động vào thứ Hai.',
    },
    {
      'word': 'wrap up',
      'phonetic': '/ræp ʌp/',
      'meaningVi': 'kết thúc',
      'exampleEn': 'Let’s wrap up the meeting.',
      'exampleVi': 'Hãy kết thúc cuộc họp.',
    },
    {
      'word': 'follow up',
      'phonetic': '/ˈfɑːloʊ ʌp/',
      'meaningVi': 'theo dõi/nhắc lại',
      'exampleEn': 'I’ll follow up by email.',
      'exampleVi': 'Tôi sẽ theo dõi qua email.',
    },
    {
      'word': 'stakeholder',
      'phonetic': '/ˈsteɪkˌhoʊldər/',
      'meaningVi': 'bên liên quan',
      'exampleEn': 'All stakeholders agreed.',
      'exampleVi': 'Tất cả bên liên quan đã đồng ý.',
    },
    {
      'word': 'deliverable',
      'phonetic': '/dɪˈlɪvərəbl/',
      'meaningVi': 'sản phẩm bàn giao',
      'exampleEn': 'The deliverables are listed.',
      'exampleVi': 'Các sản phẩm bàn giao đã liệt kê.',
    },
    {
      'word': 'scope',
      'phonetic': '/skoʊp/',
      'meaningVi': 'phạm vi',
      'exampleEn': 'Define the project scope.',
      'exampleVi': 'Xác định phạm vi dự án.',
    },
    {
      'word': 'objective',
      'phonetic': '/əbˈdʒektɪv/',
      'meaningVi': 'mục tiêu',
      'exampleEn': 'Our objective is quality.',
      'exampleVi': 'Mục tiêu của ta là chất lượng.',
    },
    {
      'word': 'priority',
      'phonetic': '/praɪˈɔːrəti/',
      'meaningVi': 'ưu tiên',
      'exampleEn': 'What’s our top priority?',
      'exampleVi': 'Ưu tiên hàng đầu là gì?',
    },
    {
      'word': 'resource',
      'phonetic': '/ˈriːsɔːrs/',
      'meaningVi': 'nguồn lực',
      'exampleEn': 'Allocate enough resources.',
      'exampleVi': 'Phân bổ đủ nguồn lực.',
    },
    {
      'word': 'allocate',
      'phonetic': '/ˈæləkeɪt/',
      'meaningVi': 'phân bổ',
      'exampleEn': 'Funds were allocated fairly.',
      'exampleVi': 'Quỹ được phân bổ công bằng.',
    },
    {
      'word': 'backlog',
      'phonetic': '/ˈbæklɔːɡ/',
      'meaningVi': 'công việc tồn',
      'exampleEn': 'Clear the backlog this week.',
      'exampleVi': 'Dọn tồn đọng tuần này.',
    },
    {
      'word': 'progress',
      'phonetic': '/ˈprɑːɡres/',
      'meaningVi': 'tiến độ; tiến triển',
      'exampleEn': 'We made good progress.',
      'exampleVi': 'Chúng tôi đã tiến triển tốt.',
    },
    {
      'word': 'update',
      'phonetic': '/ˈʌpdeɪt/',
      'meaningVi': 'cập nhật',
      'exampleEn': 'Share a status update.',
      'exampleVi': 'Chia sẻ cập nhật trạng thái.',
    },
    {
      'word': 'postpone',
      'phonetic': '/poʊˈspoʊn/',
      'meaningVi': 'hoãn',
      'exampleEn': 'Postpone the review.',
      'exampleVi': 'Hoãn buổi rà soát.',
    },
    {
      'word': 'reschedule',
      'phonetic': '/ˌriːˈskedʒuːl/',
      'meaningVi': 'dời lịch',
      'exampleEn': 'We rescheduled to Friday.',
      'exampleVi': 'Ta dời lịch sang thứ Sáu.',
    },
    {
      'word': 'venue',
      'phonetic': '/ˈvenjuː/',
      'meaningVi': 'địa điểm',
      'exampleEn': 'The venue changed.',
      'exampleVi': 'Địa điểm đã thay đổi.',
    },
    {
      'word': 'facilitator',
      'phonetic': '/fəˈsɪlɪteɪtər/',
      'meaningVi': 'điều phối viên',
      'exampleEn': 'She is the facilitator.',
      'exampleVi': 'Cô ấy là điều phối viên.',
    },
    {
      'word': 'remote',
      'phonetic': '/rɪˈmoʊt/',
      'meaningVi': 'từ xa',
      'exampleEn': 'We held a remote meeting.',
      'exampleVi': 'Ta tổ chức họp từ xa.',
    },
    {
      'word': 'on-site',
      'phonetic': '/ˌɒn ˈsaɪt/',
      'meaningVi': 'tại chỗ',
      'exampleEn': 'On-site support is available.',
      'exampleVi': 'Có hỗ trợ tại chỗ.',
    },
    {
      'word': 'conference room',
      'phonetic': '/ˈkɒnfərəns ruːm/',
      'meaningVi': 'phòng họp',
      'exampleEn': 'Book the conference room.',
      'exampleVi': 'Đặt phòng họp.',
    },
    {
      'word': 'projector',
      'phonetic': '/prəˈdʒektər/',
      'meaningVi': 'máy chiếu',
      'exampleEn': 'The projector is ready.',
      'exampleVi': 'Máy chiếu sẵn sàng.',
    },
    {
      'word': 'handout',
      'phonetic': '/ˈhændaʊt/',
      'meaningVi': 'tài liệu phát tay',
      'exampleEn': 'Print the handouts.',
      'exampleVi': 'In tài liệu phát tay.',
    },
  ];

  // =========================================================
  // Vocab 2: Customer Service & Complaints (30 thẻ) — vocab2.pdf
  // =========================================================
  final vocab2 = <Map<String, String>>[
    {
      'word': 'inquiry',
      'phonetic': '/ɪnˈkwaɪəri/',
      'meaningVi': 'yêu cầu thông tin',
      'exampleEn': 'We received your inquiry.',
      'exampleVi': 'Chúng tôi đã nhận yêu cầu thông tin.',
    },
    {
      'word': 'complaint',
      'phonetic': '/kəmˈpleɪnt/',
      'meaningVi': 'phàn nàn',
      'exampleEn': 'File a complaint online.',
      'exampleVi': 'Nộp khiếu nại trực tuyến.',
    },
    {
      'word': 'resolve',
      'phonetic': '/rɪˈzɒlv/',
      'meaningVi': 'giải quyết',
      'exampleEn': 'We resolved the issue.',
      'exampleVi': 'Chúng tôi đã giải quyết sự cố.',
    },
    {
      'word': 'apologize',
      'phonetic': '/əˈpɒlədʒaɪz/',
      'meaningVi': 'xin lỗi',
      'exampleEn': 'We apologize for the delay.',
      'exampleVi': 'Chúng tôi xin lỗi vì sự chậm trễ.',
    },
    {
      'word': 'refund',
      'phonetic': '/ˈriːfʌnd/',
      'meaningVi': 'hoàn tiền',
      'exampleEn': 'Request a full refund.',
      'exampleVi': 'Yêu cầu hoàn tiền toàn bộ.',
    },
    {
      'word': 'replacement',
      'phonetic': '/rɪˈpleɪsmənt/',
      'meaningVi': 'hàng thay thế',
      'exampleEn': 'We sent a replacement.',
      'exampleVi': 'Chúng tôi đã gửi hàng thay thế.',
    },
    {
      'word': 'warranty',
      'phonetic': '/ˈwɒrənti/',
      'meaningVi': 'bảo hành',
      'exampleEn': 'It’s under warranty.',
      'exampleVi': 'Nó còn bảo hành.',
    },
    {
      'word': 'defective',
      'phonetic': '/dɪˈfektɪv/',
      'meaningVi': 'lỗi, khiếm khuyết',
      'exampleEn': 'The product is defective.',
      'exampleVi': 'Sản phẩm bị lỗi.',
    },
    {
      'word': 'damaged',
      'phonetic': '/ˈdæmɪdʒd/',
      'meaningVi': 'hư hại',
      'exampleEn': 'The package arrived damaged.',
      'exampleVi': 'Kiện hàng đến nơi bị hư.',
    },
    {
      'word': 'delay',
      'phonetic': '/dɪˈleɪ/',
      'meaningVi': 'chậm trễ',
      'exampleEn': 'We regret the delay.',
      'exampleVi': 'Chúng tôi tiếc vì sự chậm trễ.',
    },
    {
      'word': 'shipping',
      'phonetic': '/ˈʃɪpɪŋ/',
      'meaningVi': 'vận chuyển',
      'exampleEn': 'Free shipping is offered.',
      'exampleVi': 'Có vận chuyển miễn phí.',
    },
    {
      'word': 'tracking number',
      'phonetic': '/ˈtrækɪŋ ˌnʌmbər/',
      'meaningVi': 'mã theo dõi',
      'exampleEn': 'What’s the tracking number?',
      'exampleVi': 'Mã theo dõi là gì?',
    },
    {
      'word': 'support ticket',
      'phonetic': '/səˈpɔːrt ˈtɪkɪt/',
      'meaningVi': 'phiếu hỗ trợ',
      'exampleEn': 'Create a support ticket.',
      'exampleVi': 'Tạo phiếu hỗ trợ.',
    },
    {
      'word': 'escalate',
      'phonetic': '/ˈeskəleɪt/',
      'meaningVi': 'leo thang/chuyển cấp',
      'exampleEn': 'We escalated the case.',
      'exampleVi': 'Chúng tôi đã chuyển cấp vụ việc.',
    },
    {
      'word': 'supervisor',
      'phonetic': '/ˈsuːpərvaɪzər/',
      'meaningVi': 'giám sát',
      'exampleEn': 'Ask to speak to a supervisor.',
      'exampleVi': 'Yêu cầu gặp giám sát.',
    },
    {
      'word': 'policy',
      'phonetic': '/ˈpɒlɪsi/',
      'meaningVi': 'chính sách',
      'exampleEn': 'Read our return policy.',
      'exampleVi': 'Đọc chính sách đổi trả.',
    },
    {
      'word': 'satisfaction',
      'phonetic': '/ˌsætɪsˈfækʃn/',
      'meaningVi': 'sự hài lòng',
      'exampleEn': 'Customer satisfaction is key.',
      'exampleVi': 'Sự hài lòng khách hàng là then chốt.',
    },
    {
      'word': 'feedback',
      'phonetic': '/ˈfiːdbæk/',
      'meaningVi': 'phản hồi',
      'exampleEn': 'We value your feedback.',
      'exampleVi': 'Chúng tôi trân trọng phản hồi của bạn.',
    },
    {
      'word': 'survey',
      'phonetic': '/ˈsɜːrveɪ/',
      'meaningVi': 'khảo sát',
      'exampleEn': 'Please fill out the survey.',
      'exampleVi': 'Vui lòng điền khảo sát.',
    },
    {
      'word': 'response time',
      'phonetic': '/rɪˈspɒns taɪm/',
      'meaningVi': 'thời gian phản hồi',
      'exampleEn': 'Our response time is 24h.',
      'exampleVi': 'Thời gian phản hồi là 24h.',
    },
    {
      'word': 'hold time',
      'phonetic': '/hoʊld taɪm/',
      'meaningVi': 'thời gian chờ máy',
      'exampleEn': 'Sorry for the long hold time.',
      'exampleVi': 'Xin lỗi vì chờ máy lâu.',
    },
    {
      'word': 'courteous',
      'phonetic': '/ˈkɜːrtiəs/',
      'meaningVi': 'lịch sự, nhã nhặn',
      'exampleEn': 'Be courteous to customers.',
      'exampleVi': 'Hãy lịch sự với khách.',
    },
    {
      'word': 'inconvenient',
      'phonetic': '/ˌɪnkənˈviːniənt/',
      'meaningVi': 'bất tiện',
      'exampleEn': 'That was inconvenient for you.',
      'exampleVi': 'Điều đó gây bất tiện cho bạn.',
    },
    {
      'word': 'misunderstanding',
      'phonetic': '/ˌmɪsʌndərˈstændɪŋ/',
      'meaningVi': 'hiểu lầm',
      'exampleEn': 'It was a misunderstanding.',
      'exampleVi': 'Đó là hiểu lầm.',
    },
    {
      'word': 'goodwill',
      'phonetic': '/ˌɡʊdˈwɪl/',
      'meaningVi': 'thiện chí',
      'exampleEn': 'Offer a goodwill credit.',
      'exampleVi': 'Cung cấp khoản tín dụng thiện chí.',
    },
    {
      'word': 'credit',
      'phonetic': '/ˈkredɪt/',
      'meaningVi': 'khoản tín/dư có',
      'exampleEn': 'We issued a credit.',
      'exampleVi': 'Chúng tôi đã cấp tín dụng.',
    },
    {
      'word': 'store credit',
      'phonetic': '/stɔːr ˈkredɪt/',
      'meaningVi': 'tín dụng cửa hàng',
      'exampleEn': 'Use your store credit.',
      'exampleVi': 'Dùng tín dụng cửa hàng của bạn.',
    },
    {
      'word': 'compensation',
      'phonetic': '/ˌkɒmpenˈseɪʃn/',
      'meaningVi': 'đền bù',
      'exampleEn': 'We offer compensation.',
      'exampleVi': 'Chúng tôi đề nghị đền bù.',
    },
    {
      'word': 'return',
      'phonetic': '/rɪˈtɜːrn/',
      'meaningVi': 'trả hàng; hàng trả',
      'exampleEn': 'Return the item within 7 days.',
      'exampleVi': 'Trả hàng trong 7 ngày.',
    },
    {
      'word': 'exchange',
      'phonetic': '/ɪksˈtʃeɪndʒ/',
      'meaningVi': 'đổi hàng',
      'exampleEn': 'Exchange is available.',
      'exampleVi': 'Có thể đổi hàng.',
    },
  ];

  // =========================================================
  // Vocab 3: Business Travel & Lodging (30 thẻ) — vocab3.pdf
  // =========================================================
  final vocab3 = <Map<String, String>>[
    {
      'word': 'itinerary',
      'phonetic': '/aɪˈtɪnərɛri/',
      'meaningVi': 'lịch trình',
      'exampleEn': 'Send me your itinerary.',
      'exampleVi': 'Gửi tôi lịch trình của bạn.',
    },
    {
      'word': 'boarding pass',
      'phonetic': '/ˈbɔːrdɪŋ pæs/',
      'meaningVi': 'thẻ lên máy bay',
      'exampleEn': 'Print your boarding pass.',
      'exampleVi': 'In thẻ lên máy bay.',
    },
    {
      'word': 'check-in',
      'phonetic': '/ˈtʃek ɪn/',
      'meaningVi': 'làm thủ tục vào',
      'exampleEn': 'Check in online.',
      'exampleVi': 'Làm thủ tục online.',
    },
    {
      'word': 'check-out',
      'phonetic': '/ˈtʃek aʊt/',
      'meaningVi': 'trả phòng; kết sổ',
      'exampleEn': 'Check out at noon.',
      'exampleVi': 'Trả phòng lúc trưa.',
    },
    {
      'word': 'luggage',
      'phonetic': '/ˈlʌɡɪdʒ/',
      'meaningVi': 'hành lý',
      'exampleEn': 'Keep your luggage nearby.',
      'exampleVi': 'Giữ hành lý gần bên.',
    },
    {
      'word': 'baggage claim',
      'phonetic': '/ˈbæɡɪdʒ kleɪm/',
      'meaningVi': 'băng nhận hành lý',
      'exampleEn': 'Go to baggage claim B.',
      'exampleVi': 'Đi đến băng nhận B.',
    },
    {
      'word': 'carry-on',
      'phonetic': '/ˈkæri ɒn/',
      'meaningVi': 'xách tay',
      'exampleEn': 'One carry-on per person.',
      'exampleVi': 'Mỗi người một hành lý xách tay.',
    },
    {
      'word': 'gate',
      'phonetic': '/ɡeɪt/',
      'meaningVi': 'cổng',
      'exampleEn': 'Your gate is A12.',
      'exampleVi': 'Cổng của bạn là A12.',
    },
    {
      'word': 'departure',
      'phonetic': '/dɪˈpɑːrtʃər/',
      'meaningVi': 'khởi hành',
      'exampleEn': 'Departure is at 8 a.m.',
      'exampleVi': 'Khởi hành lúc 8 giờ sáng.',
    },
    {
      'word': 'arrival',
      'phonetic': '/əˈraɪvl/',
      'meaningVi': 'đến nơi',
      'exampleEn': 'Arrival is delayed.',
      'exampleVi': 'Giờ đến bị trễ.',
    },
    {
      'word': 'layover',
      'phonetic': '/ˈleɪoʊvər/',
      'meaningVi': 'quá cảnh',
      'exampleEn': 'A 2-hour layover in Seoul.',
      'exampleVi': 'Quá cảnh 2 giờ ở Seoul.',
    },
    {
      'word': 'shuttle',
      'phonetic': '/ˈʃʌtl/',
      'meaningVi': 'xe trung chuyển',
      'exampleEn': 'Take the hotel shuttle.',
      'exampleVi': 'Đi xe trung chuyển khách sạn.',
    },
    {
      'word': 'reservation',
      'phonetic': '/ˌrezərˈveɪʃn/',
      'meaningVi': 'đặt chỗ',
      'exampleEn': 'Confirm your reservation.',
      'exampleVi': 'Xác nhận đặt chỗ.',
    },
    {
      'word': 'confirmation',
      'phonetic': '/ˌkɒnfərˈmeɪʃn/',
      'meaningVi': 'xác nhận',
      'exampleEn': 'I need a confirmation email.',
      'exampleVi': 'Tôi cần email xác nhận.',
    },
    {
      'word': 'voucher',
      'phonetic': '/ˈvaʊtʃər/',
      'meaningVi': 'phiếu, chứng từ',
      'exampleEn': 'Present the voucher at check-in.',
      'exampleVi': 'Xuất trình phiếu khi làm thủ tục.',
    },
    {
      'word': 'upgrade',
      'phonetic': '/ˈʌpɡreɪd/',
      'meaningVi': 'nâng hạng',
      'exampleEn': 'We got a free upgrade.',
      'exampleVi': 'Chúng tôi được nâng hạng miễn phí.',
    },
    {
      'word': 'economy class',
      'phonetic': '/ɪˈkɒnəmi klæs/',
      'meaningVi': 'hạng phổ thông',
      'exampleEn': 'I’m in economy class.',
      'exampleVi': 'Tôi ở hạng phổ thông.',
    },
    {
      'word': 'aisle seat',
      'phonetic': '/aɪl siːt/',
      'meaningVi': 'ghế lối đi',
      'exampleEn': 'I prefer an aisle seat.',
      'exampleVi': 'Tôi thích ghế lối đi.',
    },
    {
      'word': 'window seat',
      'phonetic': '/ˈwɪndoʊ siːt/',
      'meaningVi': 'ghế cửa sổ',
      'exampleEn': 'She wants a window seat.',
      'exampleVi': 'Cô ấy muốn ghế cửa sổ.',
    },
    {
      'word': 'delayed',
      'phonetic': '/dɪˈleɪd/',
      'meaningVi': 'bị trễ',
      'exampleEn': 'The flight is delayed.',
      'exampleVi': 'Chuyến bay bị trễ.',
    },
    {
      'word': 'canceled',
      'phonetic': '/ˈkænsəld/',
      'meaningVi': 'bị hủy',
      'exampleEn': 'The flight was canceled.',
      'exampleVi': 'Chuyến bay đã bị hủy.',
    },
    {
      'word': 'standby',
      'phonetic': '/ˈstændbaɪ/',
      'meaningVi': 'danh sách chờ',
      'exampleEn': 'I’m on standby.',
      'exampleVi': 'Tôi ở danh sách chờ.',
    },
    {
      'word': 'travel insurance',
      'phonetic': '/ˈtrævl ɪnˌʃʊrəns/',
      'meaningVi': 'bảo hiểm du lịch',
      'exampleEn': 'Buy travel insurance.',
      'exampleVi': 'Mua bảo hiểm du lịch.',
    },
    {
      'word': 'customs',
      'phonetic': '/ˈkʌstəmz/',
      'meaningVi': 'hải quan',
      'exampleEn': 'Go through customs.',
      'exampleVi': 'Làm thủ tục hải quan.',
    },
    {
      'word': 'immigration',
      'phonetic': '/ˌɪmɪˈɡreɪʃn/',
      'meaningVi': 'nhập cảnh',
      'exampleEn': 'Immigration took 20 minutes.',
      'exampleVi': 'Nhập cảnh mất 20 phút.',
    },
    {
      'word': 'passport',
      'phonetic': '/ˈpæspɔːrt/',
      'meaningVi': 'hộ chiếu',
      'exampleEn': 'Keep your passport safe.',
      'exampleVi': 'Giữ hộ chiếu an toàn.',
    },
    {
      'word': 'visa',
      'phonetic': '/ˈviːzə/',
      'meaningVi': 'thị thực',
      'exampleEn': 'Do I need a visa?',
      'exampleVi': 'Tôi có cần visa không?',
    },
    {
      'word': 'hotel amenities',
      'phonetic': '/həʊˈtel əˈmenɪtiz/',
      'meaningVi': 'tiện nghi khách sạn',
      'exampleEn': 'What amenities are included?',
      'exampleVi': 'Có những tiện nghi nào kèm theo?',
    },
    {
      'word': 'concierge',
      'phonetic': '/ˌkɒnsiˈerʒ/',
      'meaningVi': 'lễ tân hỗ trợ',
      'exampleEn': 'Ask the concierge for help.',
      'exampleVi': 'Hỏi lễ tân hỗ trợ.',
    },
    {
      'word': 'complimentary breakfast',
      'phonetic': '/ˌkɒmplɪˈmentəri ˈbrekfəst/',
      'meaningVi': 'bữa sáng miễn phí',
      'exampleEn': 'The room includes complimentary breakfast.',
      'exampleVi': 'Phòng bao gồm bữa sáng miễn phí.',
    },
  ];

  // =========================================================
  // Vocab 4: HR & Recruitment (30 thẻ) — vocab4.pdf
  // =========================================================
  final vocab4 = <Map<String, String>>[
    {
      'word': 'human resources',
      'phonetic': '/ˌhjuːmən rɪˈsɔːrsɪz/',
      'meaningVi': 'nhân sự',
      'exampleEn': 'Human resources will contact you.',
      'exampleVi': 'Phòng nhân sự sẽ liên hệ với bạn.',
    },
    {
      'word': 'recruit',
      'phonetic': '/rɪˈkruːt/',
      'meaningVi': 'tuyển dụng',
      'exampleEn': 'We plan to recruit two engineers.',
      'exampleVi': 'Chúng tôi dự định tuyển hai kỹ sư.',
    },
    {
      'word': 'recruitment',
      'phonetic': '/rɪˈkruːtmənt/',
      'meaningVi': 'quy trình tuyển',
      'exampleEn': 'Our recruitment starts next week.',
      'exampleVi': 'Quy trình tuyển dụng bắt đầu tuần sau.',
    },
    {
      'word': 'candidate',
      'phonetic': '/ˈkændɪdət/',
      'meaningVi': 'ứng viên',
      'exampleEn': 'Each candidate must submit a CV.',
      'exampleVi': 'Mỗi ứng viên phải nộp CV.',
    },
    {
      'word': 'resume',
      'phonetic': '/ˈrezjʊmeɪ/',
      'meaningVi': 'sơ yếu lý lịch',
      'exampleEn': 'Please email your resume.',
      'exampleVi': 'Vui lòng gửi CV qua email.',
    },
    {
      'word': 'CV',
      'phonetic': '/ˌsiːˈviː/',
      'meaningVi': 'hồ sơ xin việc',
      'exampleEn': 'Attach your CV to the form.',
      'exampleVi': 'Đính kèm CV vào mẫu đơn.',
    },
    {
      'word': 'cover letter',
      'phonetic': '/ˈkʌvər ˌletər/',
      'meaningVi': 'thư xin việc',
      'exampleEn': 'Write a short cover letter.',
      'exampleVi': 'Viết một thư xin việc ngắn.',
    },
    {
      'word': 'job posting',
      'phonetic': '/dʒɒb ˈpoʊstɪŋ/',
      'meaningVi': 'tin tuyển dụng',
      'exampleEn': 'I saw the job posting online.',
      'exampleVi': 'Tôi thấy tin tuyển dụng online.',
    },
    {
      'word': 'job description',
      'phonetic': '/dʒɒb dɪˈskrɪpʃn/',
      'meaningVi': 'mô tả công việc',
      'exampleEn': 'Read the job description carefully.',
      'exampleVi': 'Đọc kỹ mô tả công việc.',
    },
    {
      'word': 'requirement',
      'phonetic': '/rɪˈkwaɪərmənt/',
      'meaningVi': 'yêu cầu',
      'exampleEn': 'A degree is a key requirement.',
      'exampleVi': 'Bằng cấp là yêu cầu chính.',
    },
    {
      'word': 'qualification',
      'phonetic': '/ˌkwɒlɪfɪˈkeɪʃn/',
      'meaningVi': 'trình độ',
      'exampleEn': 'List your qualifications.',
      'exampleVi': 'Liệt kê trình độ của bạn.',
    },
    {
      'word': 'experience',
      'phonetic': '/ɪkˈspɪəriəns/',
      'meaningVi': 'kinh nghiệm',
      'exampleEn': 'We need relevant experience.',
      'exampleVi': 'Chúng tôi cần kinh nghiệm liên quan.',
    },
    {
      'word': 'skill set',
      'phonetic': '/ˈskɪl set/',
      'meaningVi': 'bộ kỹ năng',
      'exampleEn': 'Your skill set fits the role.',
      'exampleVi': 'Bộ kỹ năng của bạn phù hợp vị trí.',
    },
    {
      'word': 'shortlist',
      'phonetic': '/ˈʃɔːrtlɪst/',
      'meaningVi': 'chọn vào vòng trong',
      'exampleEn': 'We shortlisted five candidates.',
      'exampleVi': 'Chúng tôi chọn năm ứng viên vào vòng trong.',
    },
    {
      'word': 'screen',
      'phonetic': '/skriːn/',
      'meaningVi': 'sàng lọc',
      'exampleEn': 'HR will screen applications.',
      'exampleVi': 'HR sẽ sàng lọc hồ sơ.',
    },
    {
      'word': 'interview',
      'phonetic': '/ˈɪntəvjuː/',
      'meaningVi': 'phỏng vấn',
      'exampleEn': 'Your interview is on Thursday.',
      'exampleVi': 'Buổi phỏng vấn của bạn vào thứ Năm.',
    },
    {
      'word': 'panel',
      'phonetic': '/ˈpænəl/',
      'meaningVi': 'hội đồng (phỏng vấn)',
      'exampleEn': 'A panel will interview you.',
      'exampleVi': 'Một hội đồng sẽ phỏng vấn bạn.',
    },
    {
      'word': 'reference',
      'phonetic': '/ˈrefərəns/',
      'meaningVi': 'người/thư giới thiệu',
      'exampleEn': 'Provide two references.',
      'exampleVi': 'Cung cấp hai người giới thiệu.',
    },
    {
      'word': 'background check',
      'phonetic': '/ˈbækɡraʊnd tʃek/',
      'meaningVi': 'kiểm tra lý lịch',
      'exampleEn': 'We’ll conduct a background check.',
      'exampleVi': 'Chúng tôi sẽ kiểm tra lý lịch.',
    },
    {
      'word': 'offer',
      'phonetic': '/ˈɒfər/',
      'meaningVi': 'đề nghị (làm việc)',
      'exampleEn': 'They sent a job offer.',
      'exampleVi': 'Họ đã gửi đề nghị làm việc.',
    },
    {
      'word': 'compensation',
      'phonetic': '/ˌkɒmpenˈseɪʃn/',
      'meaningVi': 'đãi ngộ',
      'exampleEn': 'The compensation is competitive.',
      'exampleVi': 'Đãi ngộ cạnh tranh.',
    },
    {
      'word': 'benefits',
      'phonetic': '/ˈbenɪfɪts/',
      'meaningVi': 'phúc lợi',
      'exampleEn': 'Health benefits are included.',
      'exampleVi': 'Bao gồm phúc lợi sức khỏe.',
    },
    {
      'word': 'onboard',
      'phonetic': '/ˈɒnbɔːrd/',
      'meaningVi': 'hội nhập (nhân viên mới)',
      'exampleEn': 'We will onboard new hires.',
      'exampleVi': 'Chúng tôi sẽ hội nhập nhân viên mới.',
    },
    {
      'word': 'probation',
      'phonetic': '/prəˈbeɪʃn/',
      'meaningVi': 'thử việc',
      'exampleEn': 'The probation is two months.',
      'exampleVi': 'Thử việc trong hai tháng.',
    },
    {
      'word': 'full-time',
      'phonetic': '/ˌfʊl ˈtaɪm/',
      'meaningVi': 'toàn thời gian',
      'exampleEn': 'It’s a full-time position.',
      'exampleVi': 'Đây là vị trí toàn thời gian.',
    },
    {
      'word': 'part-time',
      'phonetic': '/ˌpɑːrt ˈtaɪm/',
      'meaningVi': 'bán thời gian',
      'exampleEn': 'Part-time roles are available.',
      'exampleVi': 'Có vị trí bán thời gian.',
    },
    {
      'word': 'intern',
      'phonetic': '/ˈɪntɜːrn/',
      'meaningVi': 'thực tập sinh',
      'exampleEn': 'We’re hiring an intern.',
      'exampleVi': 'Chúng tôi tuyển thực tập sinh.',
    },
    {
      'word': 'promotion',
      'phonetic': '/prəˈmoʊʃn/',
      'meaningVi': 'thăng chức',
      'exampleEn': 'She got a promotion.',
      'exampleVi': 'Cô ấy đã được thăng chức.',
    },
    {
      'word': 'payroll',
      'phonetic': '/ˈpeɪroʊl/',
      'meaningVi': 'bảng lương',
      'exampleEn': 'Payroll is processed monthly.',
      'exampleVi': 'Bảng lương được xử lý hàng tháng.',
    },
    {
      'word': 'turnover',
      'phonetic': '/ˈtɜːrnˌoʊvər/',
      'meaningVi': 'tỷ lệ nghỉ việc',
      'exampleEn': 'We aim to reduce turnover.',
      'exampleVi': 'Chúng tôi muốn giảm tỷ lệ nghỉ việc.',
    },
  ];

  // =========================================================
  // Vocab 5: Marketing & Sales Ops (30 thẻ) — vocab5.pdf
  // =========================================================
  final vocab5 = <Map<String, String>>[
    {
      'word': 'campaign',
      'phonetic': '/kæmˈpeɪn/',
      'meaningVi': 'chiến dịch',
      'exampleEn': 'We launched a new campaign.',
      'exampleVi': 'Chúng tôi đã tung chiến dịch mới.',
    },
    {
      'word': 'promotion',
      'phonetic': '/prəˈmoʊʃn/',
      'meaningVi': 'khuyến mãi',
      'exampleEn': 'The promotion ends Friday.',
      'exampleVi': 'Khuyến mãi kết thúc thứ Sáu.',
    },
    {
      'word': 'brochure',
      'phonetic': '/broʊˈʃʊr/',
      'meaningVi': 'tờ giới thiệu',
      'exampleEn': 'Pick up a brochure.',
      'exampleVi': 'Lấy một tờ giới thiệu.',
    },
    {
      'word': 'leaflet',
      'phonetic': '/ˈliːflət/',
      'meaningVi': 'tờ rơi',
      'exampleEn': 'They handed out leaflets.',
      'exampleVi': 'Họ phát tờ rơi.',
    },
    {
      'word': 'target audience',
      'phonetic': '/ˈtɑːrɡɪt ˈɔːdiəns/',
      'meaningVi': 'khách hàng mục tiêu',
      'exampleEn': 'Define your target audience.',
      'exampleVi': 'Xác định khách hàng mục tiêu.',
    },
    {
      'word': 'segment',
      'phonetic': '/ˈseɡmənt/',
      'meaningVi': 'phân khúc',
      'exampleEn': 'We segmented the market.',
      'exampleVi': 'Chúng tôi đã phân khúc thị trường.',
    },
    {
      'word': 'positioning',
      'phonetic': '/pəˈzɪʃənɪŋ/',
      'meaningVi': 'định vị',
      'exampleEn': 'The brand positioning is clear.',
      'exampleVi': 'Định vị thương hiệu rõ ràng.',
    },
    {
      'word': 'brand awareness',
      'phonetic': '/brænd əˈwer.nəs/',
      'meaningVi': 'nhận biết thương hiệu',
      'exampleEn': 'Increase brand awareness.',
      'exampleVi': 'Tăng nhận biết thương hiệu.',
    },
    {
      'word': 'value proposition',
      'phonetic': '/ˈvæljuː ˌprɒpəˈzɪʃn/',
      'meaningVi': 'giá trị đề xuất',
      'exampleEn': 'Refine the value proposition.',
      'exampleVi': 'Tinh chỉnh giá trị đề xuất.',
    },
    {
      'word': 'CTA',
      'phonetic': '/ˌsiː tiː ˈeɪ/',
      'meaningVi': 'lời kêu gọi hành động',
      'exampleEn': 'Add a clear CTA.',
      'exampleVi': 'Thêm lời kêu gọi rõ ràng.',
    },
    {
      'word': 'lead',
      'phonetic': '/liːd/',
      'meaningVi': 'khách tiềm năng',
      'exampleEn': 'We got 100 new leads.',
      'exampleVi': 'Chúng tôi có 100 khách tiềm năng mới.',
    },
    {
      'word': 'conversion',
      'phonetic': '/kənˈvɜːrʒn/',
      'meaningVi': 'chuyển đổi',
      'exampleEn': 'Improve conversion rate.',
      'exampleVi': 'Cải thiện tỷ lệ chuyển đổi.',
    },
    {
      'word': 'funnel',
      'phonetic': '/ˈfʌnl/',
      'meaningVi': 'phễu bán hàng',
      'exampleEn': 'Optimize the sales funnel.',
      'exampleVi': 'Tối ưu phễu bán hàng.',
    },
    {
      'word': 'pipeline',
      'phonetic': '/ˈpaɪplaɪn/',
      'meaningVi': 'đường ống cơ hội',
      'exampleEn': 'Our pipeline looks strong.',
      'exampleVi': 'Đường ống cơ hội mạnh.',
    },
    {
      'word': 'prospect',
      'phonetic': '/ˈprɒspekt/',
      'meaningVi': 'khách tiềm năng; tìm khách',
      'exampleEn': 'Call three prospects today.',
      'exampleVi': 'Gọi ba khách tiềm năng hôm nay.',
    },
    {
      'word': 'qualify',
      'phonetic': '/ˈkwɒlɪfaɪ/',
      'meaningVi': 'chấm điểm đủ chuẩn',
      'exampleEn': 'Qualify the leads first.',
      'exampleVi': 'Chấm điểm khách tiềm năng trước.',
    },
    {
      'word': 'quotation',
      'phonetic': '/kwoʊˈteɪʃn/',
      'meaningVi': 'báo giá',
      'exampleEn': 'Send a quotation by email.',
      'exampleVi': 'Gửi báo giá qua email.',
    },
    {
      'word': 'negotiation',
      'phonetic': '/nɪˌɡoʊʃiˈeɪʃn/',
      'meaningVi': 'đàm phán',
      'exampleEn': 'Prepare for negotiation.',
      'exampleVi': 'Chuẩn bị cho đàm phán.',
    },
    {
      'word': 'close',
      'phonetic': '/kloʊz/',
      'meaningVi': 'chốt (hợp đồng)',
      'exampleEn': 'We closed three deals.',
      'exampleVi': 'Chúng tôi chốt ba hợp đồng.',
    },
    {
      'word': 'upsell',
      'phonetic': '/ˈʌp.sel/',
      'meaningVi': 'bán thêm',
      'exampleEn': 'Try to upsell premium plans.',
      'exampleVi': 'Cố gắng bán thêm gói cao cấp.',
    },
    {
      'word': 'cross-sell',
      'phonetic': '/ˈkrɒs sel/',
      'meaningVi': 'bán chéo',
      'exampleEn': 'Cross-sell accessories.',
      'exampleVi': 'Bán chéo phụ kiện.',
    },
    {
      'word': 'retention',
      'phonetic': '/rɪˈtenʃn/',
      'meaningVi': 'giữ chân khách',
      'exampleEn': 'Focus on customer retention.',
      'exampleVi': 'Tập trung giữ chân khách.',
    },
    {
      'word': 'churn',
      'phonetic': '/tʃɜːrn/',
      'meaningVi': 'rời bỏ',
      'exampleEn': 'We must reduce churn.',
      'exampleVi': 'Chúng ta phải giảm rời bỏ.',
    },
    {
      'word': 'ROI',
      'phonetic': '/ˌɑːr oʊ ˈaɪ/',
      'meaningVi': 'tỷ suất lợi nhuận',
      'exampleEn': 'Report the campaign ROI.',
      'exampleVi': 'Báo cáo ROI chiến dịch.',
    },
    {
      'word': 'KPI',
      'phonetic': '/ˌkeɪ piː ˈaɪ/',
      'meaningVi': 'chỉ số hiệu suất',
      'exampleEn': 'Set KPIs for sales.',
      'exampleVi': 'Đặt KPI cho bán hàng.',
    },
    {
      'word': 'A/B test',
      'phonetic': '/ˌeɪ ˈbiː test/',
      'meaningVi': 'thử nghiệm A/B',
      'exampleEn': 'Run an A/B test.',
      'exampleVi': 'Chạy thử nghiệm A/B.',
    },
    {
      'word': 'landing page',
      'phonetic': '/ˈlændɪŋ peɪdʒ/',
      'meaningVi': 'trang đích',
      'exampleEn': 'Update the landing page copy.',
      'exampleVi': 'Cập nhật nội dung trang đích.',
    },
    {
      'word': 'testimonial',
      'phonetic': '/ˌtestɪˈmoʊniəl/',
      'meaningVi': 'lời chứng thực',
      'exampleEn': 'Add customer testimonials.',
      'exampleVi': 'Thêm lời chứng thực của khách.',
    },
    {
      'word': 'loyalty program',
      'phonetic': '/ˈlɔɪəlti ˈproʊɡræm/',
      'meaningVi': 'chương trình thân thiết',
      'exampleEn': 'Launch a loyalty program.',
      'exampleVi': 'Ra mắt chương trình thân thiết.',
    },
    {
      'word': 'distribution channel',
      'phonetic': '/dɪˌstrɪˈbjuːʃn ˈtʃænl/',
      'meaningVi': 'kênh phân phối',
      'exampleEn': 'Choose better distribution channels.',
      'exampleVi': 'Chọn kênh phân phối tốt hơn.',
    },
  ];

  // =========================================================
  // Vocab 6: Finance & Expenses (30 thẻ) — vocab6.pdf
  // =========================================================
  final vocab6 = <Map<String, String>>[
    {
      'word': 'invoice',
      'phonetic': '/ˈɪnvoɪs/',
      'meaningVi': 'hóa đơn GTGT',
      'exampleEn': 'Please issue an invoice.',
      'exampleVi': 'Vui lòng xuất hóa đơn.',
    },
    {
      'word': 'receipt',
      'phonetic': '/rɪˈsiːt/',
      'meaningVi': 'biên lai',
      'exampleEn': 'Keep the receipt for records.',
      'exampleVi': 'Giữ biên lai để lưu hồ sơ.',
    },
    {
      'word': 'expense report',
      'phonetic': '/ɪkˈspens rɪˈpɔːrt/',
      'meaningVi': 'báo cáo chi phí',
      'exampleEn': 'Submit your expense report.',
      'exampleVi': 'Nộp báo cáo chi phí của bạn.',
    },
    {
      'word': 'reimbursement',
      'phonetic': '/ˌriːɪmˈbɜːrsmənt/',
      'meaningVi': 'hoàn chi phí',
      'exampleEn': 'Claim reimbursement online.',
      'exampleVi': 'Yêu cầu hoàn chi phí online.',
    },
    {
      'word': 'budget',
      'phonetic': '/ˈbʌdʒɪt/',
      'meaningVi': 'ngân sách; lập ngân sách',
      'exampleEn': 'Stay within the budget.',
      'exampleVi': 'Ở trong phạm vi ngân sách.',
    },
    {
      'word': 'cost',
      'phonetic': '/kɔːst/',
      'meaningVi': 'chi phí',
      'exampleEn': 'Report monthly costs.',
      'exampleVi': 'Báo cáo chi phí hàng tháng.',
    },
    {
      'word': 'revenue',
      'phonetic': '/ˈrevənjuː/',
      'meaningVi': 'doanh thu',
      'exampleEn': 'Quarterly revenue increased.',
      'exampleVi': 'Doanh thu quý đã tăng.',
    },
    {
      'word': 'profit',
      'phonetic': '/ˈprɒfɪt/',
      'meaningVi': 'lợi nhuận',
      'exampleEn': 'Net profit fell slightly.',
      'exampleVi': 'Lợi nhuận ròng giảm nhẹ.',
    },
    {
      'word': 'loss',
      'phonetic': '/lɔːs/',
      'meaningVi': 'lỗ',
      'exampleEn': 'We reported a small loss.',
      'exampleVi': 'Chúng tôi ghi nhận lỗ nhỏ.',
    },
    {
      'word': 'balance',
      'phonetic': '/ˈbæl.əns/',
      'meaningVi': 'số dư/cân đối',
      'exampleEn': 'Check the account balance.',
      'exampleVi': 'Kiểm tra số dư tài khoản.',
    },
    {
      'word': 'petty cash',
      'phonetic': '/ˈpeti kæʃ/',
      'meaningVi': 'tiền mặt lặt vặt',
      'exampleEn': 'Use petty cash for snacks.',
      'exampleVi': 'Dùng quỹ lặt vặt cho đồ ăn nhẹ.',
    },
    {
      'word': 'allowance',
      'phonetic': '/əˈlaʊəns/',
      'meaningVi': 'khoản phụ cấp',
      'exampleEn': 'Travel allowance is fixed.',
      'exampleVi': 'Phụ cấp đi lại là cố định.',
    },
    {
      'word': 'approval',
      'phonetic': '/əˈpruːvl/',
      'meaningVi': 'phê duyệt',
      'exampleEn': 'Manager approval is required.',
      'exampleVi': 'Cần phê duyệt của quản lý.',
    },
    {
      'word': 'audit',
      'phonetic': '/ˈɔːdɪt/',
      'meaningVi': 'kiểm toán',
      'exampleEn': 'We have an external audit.',
      'exampleVi': 'Chúng ta có kiểm toán bên ngoài.',
    },
    {
      'word': 'ledger',
      'phonetic': '/ˈledʒər/',
      'meaningVi': 'sổ cái',
      'exampleEn': 'Record it in the ledger.',
      'exampleVi': 'Ghi vào sổ cái.',
    },
    {
      'word': 'statement',
      'phonetic': '/ˈsteɪtmənt/',
      'meaningVi': 'sao kê/bản kê',
      'exampleEn': 'Read the monthly statement.',
      'exampleVi': 'Đọc sao kê hàng tháng.',
    },
    {
      'word': 'due date',
      'phonetic': '/duː deɪt/',
      'meaningVi': 'ngày đến hạn',
      'exampleEn': 'The due date is the 15th.',
      'exampleVi': 'Ngày đến hạn là ngày 15.',
    },
    {
      'word': 'overdue',
      'phonetic': '/ˌoʊvərˈduː/',
      'meaningVi': 'quá hạn',
      'exampleEn': 'The invoice is overdue.',
      'exampleVi': 'Hóa đơn đã quá hạn.',
    },
    {
      'word': 'installment',
      'phonetic': '/ɪnˈstɔːlmənt/',
      'meaningVi': 'trả góp',
      'exampleEn': 'Pay in three installments.',
      'exampleVi': 'Trả góp trong ba kỳ.',
    },
    {
      'word': 'wire transfer',
      'phonetic': '/ˈwaɪr ˌtrænsfər/',
      'meaningVi': 'chuyển khoản',
      'exampleEn': 'We sent a wire transfer.',
      'exampleVi': 'Chúng tôi đã chuyển khoản.',
    },
    {
      'word': 'bank fee',
      'phonetic': '/bæŋk fiː/',
      'meaningVi': 'phí ngân hàng',
      'exampleEn': 'Bank fees will apply.',
      'exampleVi': 'Áp dụng phí ngân hàng.',
    },
    {
      'word': 'exchange rate',
      'phonetic': '/ɪksˈtʃeɪndʒ reɪt/',
      'meaningVi': 'tỷ giá hối đoái',
      'exampleEn': 'Check the exchange rate.',
      'exampleVi': 'Kiểm tra tỷ giá hối đoái.',
    },
    {
      'word': 'tax',
      'phonetic': '/tæks/',
      'meaningVi': 'thuế',
      'exampleEn': 'This price excludes tax.',
      'exampleVi': 'Giá này chưa gồm thuế.',
    },
    {
      'word': 'withhold',
      'phonetic': '/wɪðˈhoʊld/',
      'meaningVi': 'khấu trừ',
      'exampleEn': 'We will withhold 10% tax.',
      'exampleVi': 'Chúng tôi sẽ khấu trừ 10% thuế.',
    },
    {
      'word': 'debit',
      'phonetic': '/ˈdebɪt/',
      'meaningVi': 'ghi nợ',
      'exampleEn': 'Debit this expense.',
      'exampleVi': 'Ghi nợ chi phí này.',
    },
    {
      'word': 'credit',
      'phonetic': '/ˈkredɪt/',
      'meaningVi': 'ghi có',
      'exampleEn': 'Credit the refund.',
      'exampleVi': 'Ghi có khoản hoàn tiền.',
    },
    {
      'word': 'cash flow',
      'phonetic': '/ˈkæʃ floʊ/',
      'meaningVi': 'dòng tiền',
      'exampleEn': 'Maintain positive cash flow.',
      'exampleVi': 'Duy trì dòng tiền dương.',
    },
    {
      'word': 'forecast',
      'phonetic': '/ˈfɔːrkæst/',
      'meaningVi': 'dự báo',
      'exampleEn': 'Forecast expenses quarterly.',
      'exampleVi': 'Dự báo chi phí theo quý.',
    },
    {
      'word': 'margin',
      'phonetic': '/ˈmɑːrdʒɪn/',
      'meaningVi': 'biên lợi nhuận',
      'exampleEn': 'Protect the margin.',
      'exampleVi': 'Bảo vệ biên lợi nhuận.',
    },
    {
      'word': 'break-even',
      'phonetic': '/breɪk ˈiːvn/',
      'meaningVi': 'hòa vốn',
      'exampleEn': 'We aim to break even.',
      'exampleVi': 'Chúng tôi đặt mục tiêu hòa vốn.',
    },
  ];

  // =========================================================
  // Vocab 7: Procurement & Inventory (30 thẻ) — vocab7.pdf
  // =========================================================
  final vocab7 = <Map<String, String>>[
    {
      'word': 'procurement',
      'phonetic': '/prəˈkjʊəmənt/',
      'meaningVi': 'mua sắm (doanh nghiệp)',
      'exampleEn': 'Our procurement team reviewed bids.',
      'exampleVi': 'Đội mua sắm đã xem xét các hồ sơ thầu.',
    },
    {
      'word': 'purchase order',
      'phonetic': '/ˈpɜːtʃəs ˈɔːrdər/',
      'meaningVi': 'đơn đặt hàng',
      'exampleEn': 'Issue a purchase order today.',
      'exampleVi': 'Phát hành đơn đặt hàng hôm nay.',
    },
    {
      'word': 'supplier',
      'phonetic': '/səˈplaɪər/',
      'meaningVi': 'nhà cung cấp',
      'exampleEn': 'We negotiated with a new supplier.',
      'exampleVi': 'Chúng tôi đã đàm phán với nhà cung cấp mới.',
    },
    {
      'word': 'vendor',
      'phonetic': '/ˈvendər/',
      'meaningVi': 'nhà bán',
      'exampleEn': 'Vendors must sign the contract.',
      'exampleVi': 'Các nhà bán phải ký hợp đồng.',
    },
    {
      'word': 'quotation',
      'phonetic': '/kwoʊˈteɪʃn/',
      'meaningVi': 'báo giá',
      'exampleEn': 'We requested three quotations.',
      'exampleVi': 'Chúng tôi đã yêu cầu ba báo giá.',
    },
    {
      'word': 'bid',
      'phonetic': '/bɪd/',
      'meaningVi': 'hồ sơ thầu; đấu thầu',
      'exampleEn': 'They submitted a competitive bid.',
      'exampleVi': 'Họ nộp hồ sơ thầu cạnh tranh.',
    },
    {
      'word': 'tender',
      'phonetic': '/ˈtendər/',
      'meaningVi': 'đấu thầu',
      'exampleEn': 'The project goes to tender next month.',
      'exampleVi': 'Dự án sẽ đấu thầu tháng tới.',
    },
    {
      'word': 'RFP',
      'phonetic': '/ˌɑːr ɛf ˈpiː/',
      'meaningVi': 'yêu cầu đề xuất',
      'exampleEn': 'We issued an RFP to vendors.',
      'exampleVi': 'Chúng tôi đã phát hành RFP cho nhà bán.',
    },
    {
      'word': 'RFQ',
      'phonetic': '/ˌɑːr ɛf ˈkjuː/',
      'meaningVi': 'yêu cầu báo giá',
      'exampleEn': 'Send an RFQ for components.',
      'exampleVi': 'Gửi RFQ cho các linh kiện.',
    },
    {
      'word': 'lead time',
      'phonetic': '/ˈliːd taɪm/',
      'meaningVi': 'thời gian cung ứng',
      'exampleEn': 'The lead time is two weeks.',
      'exampleVi': 'Thời gian cung ứng là hai tuần.',
    },
    {
      'word': 'MOQ',
      'phonetic': '/ˌem oʊ ˈkjuː/',
      'meaningVi': 'số lượng tối thiểu',
      'exampleEn': 'MOQ is 100 units.',
      'exampleVi': 'MOQ là 100 đơn vị.',
    },
    {
      'word': 'unit price',
      'phonetic': '/ˈjuːnɪt praɪs/',
      'meaningVi': 'đơn giá',
      'exampleEn': 'Negotiate a lower unit price.',
      'exampleVi': 'Đàm phán đơn giá thấp hơn.',
    },
    {
      'word': 'bulk order',
      'phonetic': '/bʌlk ˈɔːrdər/',
      'meaningVi': 'đơn hàng số lượng lớn',
      'exampleEn': 'We placed a bulk order.',
      'exampleVi': 'Chúng tôi đã đặt đơn hàng số lượng lớn.',
    },
    {
      'word': 'inventory',
      'phonetic': '/ˈɪnvəntɔːri/',
      'meaningVi': 'tồn kho',
      'exampleEn': 'Inventory levels are high.',
      'exampleVi': 'Mức tồn kho đang cao.',
    },
    {
      'word': 'stock',
      'phonetic': '/stɒk/',
      'meaningVi': 'hàng tồn; dự trữ',
      'exampleEn': 'We stock spare parts.',
      'exampleVi': 'Chúng tôi dự trữ linh kiện.',
    },
    {
      'word': 'stockout',
      'phonetic': '/ˈstɒkaʊt/',
      'meaningVi': 'hết hàng',
      'exampleEn': 'We must avoid stockouts.',
      'exampleVi': 'Chúng ta phải tránh hết hàng.',
    },
    {
      'word': 'backorder',
      'phonetic': '/ˈbækˌɔːrdər/',
      'meaningVi': 'đơn hàng chờ',
      'exampleEn': 'Items are on backorder.',
      'exampleVi': 'Mặt hàng đang ở trạng thái chờ.',
    },
    {
      'word': 'reorder point',
      'phonetic': '/riːˈɔːrdər pɔɪnt/',
      'meaningVi': 'điểm đặt hàng lại',
      'exampleEn': 'Set a lower reorder point.',
      'exampleVi': 'Đặt điểm đặt lại thấp hơn.',
    },
    {
      'word': 'safety stock',
      'phonetic': '/ˈseɪfti stɒk/',
      'meaningVi': 'tồn kho an toàn',
      'exampleEn': 'Keep safety stock for peaks.',
      'exampleVi': 'Giữ tồn kho an toàn cho cao điểm.',
    },
    {
      'word': 'warehouse',
      'phonetic': '/ˈwerhaʊs/',
      'meaningVi': 'kho',
      'exampleEn': 'Goods are stored in the warehouse.',
      'exampleVi': 'Hàng được lưu ở kho.',
    },
    {
      'word': 'fulfillment',
      'phonetic': '/fʊlˈfɪlmənt/',
      'meaningVi': 'xử lý đơn hàng',
      'exampleEn': 'Fulfillment will start tomorrow.',
      'exampleVi': 'Xử lý đơn hàng sẽ bắt đầu ngày mai.',
    },
    {
      'word': 'receipt of goods',
      'phonetic': '/rɪˈsiːt əv ɡʊdz/',
      'meaningVi': 'biên nhận hàng',
      'exampleEn': 'Sign the receipt of goods.',
      'exampleVi': 'Ký biên nhận hàng hóa.',
    },
    {
      'word': 'inspection',
      'phonetic': '/ɪnˈspekʃn/',
      'meaningVi': 'kiểm định',
      'exampleEn': 'All items passed inspection.',
      'exampleVi': 'Tất cả mặt hàng đã qua kiểm định.',
    },
    {
      'word': 'defect',
      'phonetic': '/ˈdiːfekt/',
      'meaningVi': 'lỗi',
      'exampleEn': 'Report any defects immediately.',
      'exampleVi': 'Báo cáo lỗi ngay lập tức.',
    },
    {
      'word': 'return merchandise authorization',
      'phonetic': '/rɪˈtɜːrn ˈmɜːrtʃəndaɪz ˌɔːθəraɪˈzeɪʃn/',
      'meaningVi': 'mã trả hàng (RMA)',
      'exampleEn': 'Request an RMA number.',
      'exampleVi': 'Yêu cầu mã RMA.',
    },
    {
      'word': 'lot number',
      'phonetic': '/lɒt ˈnʌmbər/',
      'meaningVi': 'mã lô',
      'exampleEn': 'Record the lot number.',
      'exampleVi': 'Ghi lại mã lô.',
    },
    {
      'word': 'SKU',
      'phonetic': '/ˌes keɪ ˈjuː/',
      'meaningVi': 'mã hàng',
      'exampleEn': 'Each SKU has a barcode.',
      'exampleVi': 'Mỗi mã hàng có mã vạch.',
    },
    {
      'word': 'first-in, first-out',
      'phonetic': '/fɜːrst ɪn fɜːrst aʊt/',
      'meaningVi': 'nhập trước xuất trước (FIFO)',
      'exampleEn': 'Use FIFO for perishables.',
      'exampleVi': 'Dùng FIFO cho hàng dễ hỏng.',
    },
    {
      'word': 'purchase agreement',
      'phonetic': '/ˈpɜːtʃəs əˈɡriːmənt/',
      'meaningVi': 'hợp đồng mua',
      'exampleEn': 'Review the purchase agreement.',
      'exampleVi': 'Xem lại hợp đồng mua.',
    },
    {
      'word': 'terms & conditions',
      'phonetic': '/tɜːrmz ən kənˈdɪʃnz/',
      'meaningVi': 'điều khoản & điều kiện',
      'exampleEn': 'Check the terms and conditions.',
      'exampleVi': 'Kiểm tra điều khoản và điều kiện.',
    },
  ];

  // =========================================================
  // Vocab 8: Facilities & Maintenance (30 thẻ) — vocab8.pdf
  // =========================================================
  final vocab8 = <Map<String, String>>[
    {
      'word': 'facility',
      'phonetic': '/fəˈsɪləti/',
      'meaningVi': 'cơ sở',
      'exampleEn': 'The facility is under renovation.',
      'exampleVi': 'Cơ sở đang được cải tạo.',
    },
    {
      'word': 'premises',
      'phonetic': '/ˈpremɪsɪz/',
      'meaningVi': 'khuôn viên',
      'exampleEn': 'Smoking is not allowed on the premises.',
      'exampleVi': 'Cấm hút thuốc trong khuôn viên.',
    },
    {
      'word': 'maintenance',
      'phonetic': '/ˈmeɪntənəns/',
      'meaningVi': 'bảo trì',
      'exampleEn': 'Schedule regular maintenance.',
      'exampleVi': 'Lên lịch bảo trì định kỳ.',
    },
    {
      'word': 'repair',
      'phonetic': '/rɪˈper/',
      'meaningVi': 'sửa chữa',
      'exampleEn': 'The elevator needs repair.',
      'exampleVi': 'Thang máy cần sửa.',
    },
    {
      'word': 'inspection',
      'phonetic': '/ɪnˈspekʃn/',
      'meaningVi': 'kiểm tra',
      'exampleEn': 'Conduct a safety inspection.',
      'exampleVi': 'Tiến hành kiểm tra an toàn.',
    },
    {
      'word': 'work order',
      'phonetic': '/wɜːrk ˈɔːrdər/',
      'meaningVi': 'phiếu công việc',
      'exampleEn': 'Create a work order for HVAC.',
      'exampleVi': 'Tạo phiếu công việc cho hệ HVAC.',
    },
    {
      'word': 'HVAC',
      'phonetic': '/ˌeɪtʃ viː eɪ ˈsiː/',
      'meaningVi': 'điều hòa thông gió',
      'exampleEn': 'The HVAC system was serviced.',
      'exampleVi': 'Hệ HVAC đã được bảo dưỡng.',
    },
    {
      'word': 'plumbing',
      'phonetic': '/ˈplʌmɪŋ/',
      'meaningVi': 'hệ thống nước',
      'exampleEn': 'There’s a plumbing issue.',
      'exampleVi': 'Có vấn đề về nước.',
    },
    {
      'word': 'electrical',
      'phonetic': '/ɪˈlektrɪkl/',
      'meaningVi': 'điện',
      'exampleEn': 'Report any electrical hazards.',
      'exampleVi': 'Báo nguy cơ về điện.',
    },
    {
      'word': 'fixture',
      'phonetic': '/ˈfɪkstʃər/',
      'meaningVi': 'vật cố định',
      'exampleEn': 'Replace broken fixtures.',
      'exampleVi': 'Thay vật cố định bị hỏng.',
    },
    {
      'word': 'lighting',
      'phonetic': '/ˈlaɪtɪŋ/',
      'meaningVi': 'chiếu sáng',
      'exampleEn': 'Improve hallway lighting.',
      'exampleVi': 'Cải thiện chiếu sáng hành lang.',
    },
    {
      'word': 'fire alarm',
      'phonetic': '/ˈfaɪər əˈlɑːrm/',
      'meaningVi': 'báo cháy',
      'exampleEn': 'Test the fire alarm weekly.',
      'exampleVi': 'Kiểm tra báo cháy hàng tuần.',
    },
    {
      'word': 'sprinkler',
      'phonetic': '/ˈsprɪŋklər/',
      'meaningVi': 'vòi phun',
      'exampleEn': 'Sprinklers were activated.',
      'exampleVi': 'Vòi phun đã được kích hoạt.',
    },
    {
      'word': 'emergency exit',
      'phonetic': '/ɪˈmɜːrdʒənsi ˈeɡzɪt/',
      'meaningVi': 'cửa thoát hiểm',
      'exampleEn': 'Keep emergency exits clear.',
      'exampleVi': 'Giữ cửa thoát hiểm thông thoáng.',
    },
    {
      'word': 'evacuation',
      'phonetic': '/ɪˌvækjuˈeɪʃn/',
      'meaningVi': 'sơ tán',
      'exampleEn': 'An evacuation drill is scheduled.',
      'exampleVi': 'Có lịch diễn tập sơ tán.',
    },
    {
      'word': 'PPE',
      'phonetic': '/ˌpiː piː ˈiː/',
      'meaningVi': 'đồ bảo hộ',
      'exampleEn': 'Wear PPE in the workshop.',
      'exampleVi': 'Đeo đồ bảo hộ trong xưởng.',
    },
    {
      'word': 'hazard',
      'phonetic': '/ˈhæzərd/',
      'meaningVi': 'mối nguy',
      'exampleEn': 'Report chemical hazards.',
      'exampleVi': 'Báo các mối nguy hóa chất.',
    },
    {
      'word': 'spill',
      'phonetic': '/spɪl/',
      'meaningVi': 'tràn đổ',
      'exampleEn': 'Clean up the spill immediately.',
      'exampleVi': 'Dọn chỗ tràn đổ ngay.',
    },
    {
      'word': 'outage',
      'phonetic': '/ˈaʊtɪdʒ/',
      'meaningVi': 'mất điện/ngừng dịch vụ',
      'exampleEn': 'A power outage occurred.',
      'exampleVi': 'Đã xảy ra mất điện.',
    },
    {
      'word': 'shutdown',
      'phonetic': '/ˈʃʌtdaʊn/',
      'meaningVi': 'ngừng hoạt động',
      'exampleEn': 'We planned a weekend shutdown.',
      'exampleVi': 'Chúng tôi lên kế hoạch ngừng hoạt động cuối tuần.',
    },
    {
      'word': 'lockout-tagout',
      'phonetic': '/ˈlɒkaʊt ˈtæɡaʊt/',
      'meaningVi': 'quy trình khóa/ghi nhãn',
      'exampleEn': 'Follow lockout-tagout procedures.',
      'exampleVi': 'Tuân thủ quy trình khóa/ghi nhãn.',
    },
    {
      'word': 'preventive maintenance',
      'phonetic': '/prɪˈventɪv ˈmeɪntənəns/',
      'meaningVi': 'bảo trì phòng ngừa',
      'exampleEn': 'Adopt preventive maintenance.',
      'exampleVi': 'Áp dụng bảo trì phòng ngừa.',
    },
    {
      'word': 'predictive maintenance',
      'phonetic': '/prɪˈdɪktɪv ˈmeɪntənəns/',
      'meaningVi': 'bảo trì dự đoán',
      'exampleEn': 'We’re testing predictive maintenance.',
      'exampleVi': 'Chúng tôi đang thử bảo trì dự đoán.',
    },
    {
      'word': 'workplace safety',
      'phonetic': '/ˈwɜːrkpleɪs ˈseɪfti/',
      'meaningVi': 'an toàn nơi làm việc',
      'exampleEn': 'Workplace safety is a priority.',
      'exampleVi': 'An toàn nơi làm việc là ưu tiên.',
    },
    {
      'word': 'facility manager',
      'phonetic': '/fəˈsɪləti ˈmænɪdʒər/',
      'meaningVi': 'quản lý cơ sở',
      'exampleEn': 'The facility manager approved it.',
      'exampleVi': 'Quản lý cơ sở đã phê duyệt.',
    },
    {
      'word': 'janitor',
      'phonetic': '/ˈdʒænɪtər/',
      'meaningVi': 'lao công',
      'exampleEn': 'Call the janitor for cleanup.',
      'exampleVi': 'Gọi lao công để dọn dẹp.',
    },
    {
      'word': 'contractor',
      'phonetic': '/ˈkɒntræktər/',
      'meaningVi': 'nhà thầu',
      'exampleEn': 'We hired a contractor.',
      'exampleVi': 'Chúng tôi đã thuê nhà thầu.',
    },
    {
      'word': 'permit',
      'phonetic': '/ˈpɜːrmɪt/',
      'meaningVi': 'giấy phép',
      'exampleEn': 'A work permit is required.',
      'exampleVi': 'Cần giấy phép công việc.',
    },
    {
      'word': 'compliance',
      'phonetic': '/kəmˈplaɪəns/',
      'meaningVi': 'tuân thủ',
      'exampleEn': 'Ensure compliance with codes.',
      'exampleVi': 'Đảm bảo tuân thủ quy chuẩn.',
    },
    {
      'word': 'checklist',
      'phonetic': '/ˈtʃeklɪst/',
      'meaningVi': 'danh sách kiểm tra',
      'exampleEn': 'Complete the safety checklist.',
      'exampleVi': 'Hoàn thành danh sách kiểm tra an toàn.',
    },
  ];

  // =========================================================
  // Vocab 9: IT & Tech Support (30 thẻ) — vocab9.pdf
  // =========================================================
  final vocab9 = <Map<String, String>>[
    {
      'word': 'IT support',
      'phonetic': '/ˌaɪ ˈtiː səˈpɔːrt/',
      'meaningVi': 'hỗ trợ CNTT',
      'exampleEn': 'Contact IT support via ticket.',
      'exampleVi': 'Liên hệ IT qua phiếu hỗ trợ.',
    },
    {
      'word': 'help desk',
      'phonetic': '/ˈhelp desk/',
      'meaningVi': 'bàn trợ giúp',
      'exampleEn': 'The help desk is available 24/7.',
      'exampleVi': 'Bàn trợ giúp hoạt động 24/7.',
    },
    {
      'word': 'ticket',
      'phonetic': '/ˈtɪkɪt/',
      'meaningVi': 'phiếu hỗ trợ',
      'exampleEn': 'Create a new support ticket.',
      'exampleVi': 'Tạo phiếu hỗ trợ mới.',
    },
    {
      'word': 'login',
      'phonetic': '/ˈlɒɡɪn/',
      'meaningVi': 'đăng nhập',
      'exampleEn': 'Your login failed.',
      'exampleVi': 'Bạn đăng nhập thất bại.',
    },
    {
      'word': 'password',
      'phonetic': '/ˈpæswɜːrd/',
      'meaningVi': 'mật khẩu',
      'exampleEn': 'Reset your password.',
      'exampleVi': 'Đặt lại mật khẩu.',
    },
    {
      'word': 'account',
      'phonetic': '/əˈkaʊnt/',
      'meaningVi': 'tài khoản',
      'exampleEn': 'Your account is locked.',
      'exampleVi': 'Tài khoản của bạn bị khóa.',
    },
    {
      'word': 'network',
      'phonetic': '/ˈnetwɜːrk/',
      'meaningVi': 'mạng',
      'exampleEn': 'The network is down.',
      'exampleVi': 'Mạng đang bị lỗi.',
    },
    {
      'word': 'router',
      'phonetic': '/ˈruːtər/',
      'meaningVi': 'bộ định tuyến',
      'exampleEn': 'Restart the router.',
      'exampleVi': 'Khởi động lại bộ định tuyến.',
    },
    {
      'word': 'bandwidth',
      'phonetic': '/ˈbændwɪdθ/',
      'meaningVi': 'băng thông',
      'exampleEn': 'Bandwidth is limited.',
      'exampleVi': 'Băng thông bị giới hạn.',
    },
    {
      'word': 'firewall',
      'phonetic': '/ˈfaɪərwɔːl/',
      'meaningVi': 'tường lửa',
      'exampleEn': 'The firewall blocked it.',
      'exampleVi': 'Tường lửa đã chặn nó.',
    },
    {
      'word': 'VPN',
      'phonetic': '/ˌviː piː ˈen/',
      'meaningVi': 'mạng riêng ảo',
      'exampleEn': 'Connect through VPN.',
      'exampleVi': 'Kết nối qua VPN.',
    },
    {
      'word': 'update',
      'phonetic': '/ˈʌpdeɪt/',
      'meaningVi': 'cập nhật',
      'exampleEn': 'Install the latest updates.',
      'exampleVi': 'Cài đặt các bản cập nhật mới nhất.',
    },
    {
      'word': 'patch',
      'phonetic': '/pætʃ/',
      'meaningVi': 'bản vá; vá lỗi',
      'exampleEn': 'Apply a security patch.',
      'exampleVi': 'Áp dụng bản vá bảo mật.',
    },
    {
      'word': 'bug',
      'phonetic': '/bʌɡ/',
      'meaningVi': 'lỗi phần mềm',
      'exampleEn': 'We fixed a login bug.',
      'exampleVi': 'Chúng tôi đã sửa lỗi đăng nhập.',
    },
    {
      'word': 'error',
      'phonetic': '/ˈerər/',
      'meaningVi': 'lỗi',
      'exampleEn': 'An error message appeared.',
      'exampleVi': 'Hiện thông báo lỗi.',
    },
    {
      'word': 'crash',
      'phonetic': '/kræʃ/',
      'meaningVi': 'sập (ứng dụng)',
      'exampleEn': 'The app crashed twice.',
      'exampleVi': 'Ứng dụng sập hai lần.',
    },
    {
      'word': 'lag',
      'phonetic': '/læɡ/',
      'meaningVi': 'độ trễ',
      'exampleEn': 'Video calls lag at noon.',
      'exampleVi': 'Cuộc gọi video bị trễ buổi trưa.',
    },
    {
      'word': 'backup',
      'phonetic': '/ˈbækʌp/',
      'meaningVi': 'sao lưu',
      'exampleEn': 'Schedule daily backups.',
      'exampleVi': 'Lên lịch sao lưu hằng ngày.',
    },
    {
      'word': 'restore',
      'phonetic': '/rɪˈstɔːr/',
      'meaningVi': 'khôi phục',
      'exampleEn': 'Restore from yesterday’s backup.',
      'exampleVi': 'Khôi phục từ bản sao lưu hôm qua.',
    },
    {
      'word': 'cloud storage',
      'phonetic': '/klaʊd ˈstɔːrɪdʒ/',
      'meaningVi': 'lưu trữ đám mây',
      'exampleEn': 'Files are in cloud storage.',
      'exampleVi': 'Tệp nằm trong lưu trữ đám mây.',
    },
    {
      'word': 'permissions',
      'phonetic': '/pərˈmɪʃnz/',
      'meaningVi': 'quyền truy cập',
      'exampleEn': 'Adjust user permissions.',
      'exampleVi': 'Điều chỉnh quyền người dùng.',
    },
    {
      'word': 'admin',
      'phonetic': '/ˈædmɪn/',
      'meaningVi': 'quản trị viên',
      'exampleEn': 'Ask the admin to approve.',
      'exampleVi': 'Yêu cầu quản trị viên phê duyệt.',
    },
    {
      'word': 'endpoint',
      'phonetic': '/ˈendpɔɪnt/',
      'meaningVi': 'điểm cuối/kết nối',
      'exampleEn': 'The API endpoint changed.',
      'exampleVi': 'Điểm cuối API đã thay đổi.',
    },
    {
      'word': 'downtime',
      'phonetic': '/ˈdaʊntaɪm/',
      'meaningVi': 'thời gian ngừng',
      'exampleEn': 'We had one hour of downtime.',
      'exampleVi': 'Chúng tôi bị ngừng một giờ.',
    },
    {
      'word': 'SLA',
      'phonetic': '/ˌes el ˈeɪ/',
      'meaningVi': 'cam kết dịch vụ',
      'exampleEn': 'Our SLA is 99.9%.',
      'exampleVi': 'SLA của chúng tôi là 99,9%.',
    },
    {
      'word': 'ticket queue',
      'phonetic': '/ˈtɪkɪt kjuː/',
      'meaningVi': 'hàng đợi phiếu',
      'exampleEn': 'Your ticket is first in queue.',
      'exampleVi': 'Phiếu của bạn đứng đầu hàng.',
    },
    {
      'word': 'knowledge base',
      'phonetic': '/ˈnɒlɪdʒ beɪs/',
      'meaningVi': 'kho tri thức',
      'exampleEn': 'Check the knowledge base.',
      'exampleVi': 'Xem kho tri thức.',
    },
    {
      'word': 'remote access',
      'phonetic': '/rɪˈmoʊt ˈæksɛs/',
      'meaningVi': 'truy cập từ xa',
      'exampleEn': 'Enable remote access.',
      'exampleVi': 'Bật truy cập từ xa.',
    },
    {
      'word': 'two-factor authentication',
      'phonetic': '/ˌtuː ˈfæktər ɔːˌθentɪˈkeɪʃn/',
      'meaningVi': 'xác thực hai yếu tố',
      'exampleEn': 'Turn on two-factor authentication.',
      'exampleVi': 'Bật xác thực hai yếu tố.',
    },
    {
      'word': 'malware',
      'phonetic': '/ˈmælwer/',
      'meaningVi': 'phần mềm độc hại',
      'exampleEn': 'Scan for malware.',
      'exampleVi': 'Quét tìm phần mềm độc hại.',
    },
  ];

  // =========================================================
  // Vocab 10: Shipping & Delivery (30 thẻ) — vocab10.pdf
  // =========================================================
  final vocab10 = <Map<String, String>>[
    {
      'word': 'shipment',
      'phonetic': '/ˈʃɪpmənt/',
      'meaningVi': 'lô hàng',
      'exampleEn': 'The shipment arrived early.',
      'exampleVi': 'Lô hàng đã đến sớm.',
    },
    {
      'word': 'ship',
      'phonetic': '/ʃɪp/',
      'meaningVi': 'vận chuyển',
      'exampleEn': 'We will ship tomorrow.',
      'exampleVi': 'Chúng tôi sẽ vận chuyển vào ngày mai.',
    },
    {
      'word': 'courier',
      'phonetic': '/ˈkʊriər/',
      'meaningVi': 'hãng chuyển phát',
      'exampleEn': 'A courier will pick it up.',
      'exampleVi': 'Hãng chuyển phát sẽ đến lấy.',
    },
    {
      'word': 'tracking number',
      'phonetic': '/ˈtrækɪŋ ˌnʌmbər/',
      'meaningVi': 'mã theo dõi',
      'exampleEn': 'What’s the tracking number?',
      'exampleVi': 'Mã theo dõi là gì?',
    },
    {
      'word': 'waybill',
      'phonetic': '/ˈweɪbɪl/',
      'meaningVi': 'vận đơn',
      'exampleEn': 'Attach the waybill to the box.',
      'exampleVi': 'Gắn vận đơn vào thùng.',
    },
    {
      'word': 'bill of lading',
      'phonetic': '/ˌbɪl əv ˈleɪdɪŋ/',
      'meaningVi': 'vận đơn đường biển',
      'exampleEn': 'We received the bill of lading.',
      'exampleVi': 'Chúng tôi đã nhận vận đơn đường biển.',
    },
    {
      'word': 'freight',
      'phonetic': '/freɪt/',
      'meaningVi': 'hàng chở; cước vận tải',
      'exampleEn': 'Freight charges apply.',
      'exampleVi': 'Áp dụng cước vận tải.',
    },
    {
      'word': 'carrier',
      'phonetic': '/ˈkæriər/',
      'meaningVi': 'hãng vận tải',
      'exampleEn': 'Choose a reliable carrier.',
      'exampleVi': 'Chọn hãng vận tải đáng tin cậy.',
    },
    {
      'word': 'warehouse',
      'phonetic': '/ˈwerhaʊs/',
      'meaningVi': 'kho',
      'exampleEn': 'Goods left the warehouse.',
      'exampleVi': 'Hàng đã rời kho.',
    },
    {
      'word': 'pick-up',
      'phonetic': '/ˈpɪk ʌp/',
      'meaningVi': 'lấy hàng',
      'exampleEn': 'Schedule a pick-up.',
      'exampleVi': 'Lên lịch lấy hàng.',
    },
    {
      'word': 'drop-off',
      'phonetic': '/ˈdrɒp ɒf/',
      'meaningVi': 'giao/điểm gửi',
      'exampleEn': 'Use the nearest drop-off point.',
      'exampleVi': 'Dùng điểm gửi gần nhất.',
    },
    {
      'word': 'dispatch',
      'phonetic': '/dɪˈspætʃ/',
      'meaningVi': 'xuất hàng; gửi đi',
      'exampleEn': 'Orders were dispatched today.',
      'exampleVi': 'Đơn hàng đã được xuất hôm nay.',
    },
    {
      'word': 'in transit',
      'phonetic': '/ɪn ˈtrænzɪt/',
      'meaningVi': 'đang vận chuyển',
      'exampleEn': 'Your order is in transit.',
      'exampleVi': 'Đơn hàng đang vận chuyển.',
    },
    {
      'word': 'customs',
      'phonetic': '/ˈkʌstəmz/',
      'meaningVi': 'hải quan',
      'exampleEn': 'The parcel is at customs.',
      'exampleVi': 'Kiện hàng đang ở hải quan.',
    },
    {
      'word': 'duty',
      'phonetic': '/ˈdjuːti/',
      'meaningVi': 'thuế nhập khẩu',
      'exampleEn': 'Import duties may apply.',
      'exampleVi': 'Có thể áp thuế nhập khẩu.',
    },
    {
      'word': 'clearance',
      'phonetic': '/ˈklɪərəns/',
      'meaningVi': 'thông quan',
      'exampleEn': 'Customs clearance is pending.',
      'exampleVi': 'Đang chờ thông quan.',
    },
    {
      'word': 'delivery',
      'phonetic': '/dɪˈlɪvəri/',
      'meaningVi': 'giao hàng',
      'exampleEn': 'Delivery is scheduled for Friday.',
      'exampleVi': 'Lịch giao hàng là thứ Sáu.',
    },
    {
      'word': 'proof of delivery',
      'phonetic': '/pruːf əv dɪˈlɪvəri/',
      'meaningVi': 'bằng chứng giao hàng',
      'exampleEn': 'Get proof of delivery.',
      'exampleVi': 'Lấy bằng chứng giao hàng.',
    },
    {
      'word': 'recipient',
      'phonetic': '/rɪˈsɪpiənt/',
      'meaningVi': 'người nhận',
      'exampleEn': 'Confirm the recipient’s name.',
      'exampleVi': 'Xác nhận tên người nhận.',
    },
    {
      'word': 'signature required',
      'phonetic': '/ˈsɪɡnətʃər rɪˈkwaɪərd/',
      'meaningVi': 'cần chữ ký',
      'exampleEn': 'Signature required on delivery.',
      'exampleVi': 'Khi giao cần chữ ký.',
    },
    {
      'word': 'fragile',
      'phonetic': '/ˈfrædʒaɪl/',
      'meaningVi': 'dễ vỡ',
      'exampleEn': 'Label the box as fragile.',
      'exampleVi': 'Dán nhãn thùng là dễ vỡ.',
    },
    {
      'word': 'insured',
      'phonetic': '/ɪnˈʃʊrd/',
      'meaningVi': 'được bảo hiểm',
      'exampleEn': 'The parcel is insured.',
      'exampleVi': 'Kiện hàng đã được bảo hiểm.',
    },
    {
      'word': 'parcel',
      'phonetic': '/ˈpɑːrsl/',
      'meaningVi': 'bưu kiện',
      'exampleEn': 'The parcel was delayed.',
      'exampleVi': 'Bưu kiện bị trễ.',
    },
    {
      'word': 'bulk',
      'phonetic': '/bʌlk/',
      'meaningVi': 'số lượng lớn',
      'exampleEn': 'Bulk delivery on Mondays.',
      'exampleVi': 'Giao số lượng lớn vào thứ Hai.',
    },
    {
      'word': 'last-mile',
      'phonetic': '/ˌlæst ˈmaɪl/',
      'meaningVi': 'chặng cuối',
      'exampleEn': 'Improve last-mile efficiency.',
      'exampleVi': 'Cải thiện hiệu quả chặng cuối.',
    },
    {
      'word': 'ETA',
      'phonetic': '/ˌiː tiː ˈeɪ/',
      'meaningVi': 'thời gian dự kiến đến',
      'exampleEn': 'What’s the ETA for order 45?',
      'exampleVi': 'Thời gian dự kiến đến của đơn 45 là khi nào?',
    },
    {
      'word': 'return',
      'phonetic': '/rɪˈtɜːrn/',
      'meaningVi': 'trả hàng; hoàn về',
      'exampleEn': 'Arrange a return shipment.',
      'exampleVi': 'Sắp xếp lô hàng trả về.',
    },
    {
      'word': 'undeliverable',
      'phonetic': '/ˌʌndɪˈlɪvərəbl/',
      'meaningVi': 'không giao được',
      'exampleEn': 'The address is undeliverable.',
      'exampleVi': 'Không thể giao đến địa chỉ.',
    },
    {
      'word': 'reroute',
      'phonetic': '/ˌriːˈruːt/',
      'meaningVi': 'đổi tuyến',
      'exampleEn': 'Reroute the package to HQ.',
      'exampleVi': 'Đổi tuyến gói hàng về trụ sở.',
    },
    {
      'word': 'same-day',
      'phonetic': '/ˌseɪm ˈdeɪ/',
      'meaningVi': 'trong ngày',
      'exampleEn': 'We offer same-day delivery.',
      'exampleVi': 'Chúng tôi có giao trong ngày.',
    },
  ];

  // === Ghi các topic vào Firestore
  await _seedTopic(
    topicId: 'vocab1',
    topicName: 'Bài 1: Meetings & Project Workflow',
    cards: vocab1,
  );
  await _seedTopic(
    topicId: 'vocab2',
    topicName: 'Bài 2: Customer Service & Complaints',
    cards: vocab2,
  );
  await _seedTopic(
    topicId: 'vocab3',
    topicName: 'Bài 3: Business Travel & Lodging',
    cards: vocab3,
  );
  await _seedTopic(
    topicId: 'vocab4',
    topicName: 'Bài 4: HR & Recruitment',
    cards: vocab4,
  );
  await _seedTopic(
    topicId: 'vocab5',
    topicName: 'Bài 5: Marketing & Sales Ops',
    cards: vocab5,
  );
  await _seedTopic(
    topicId: 'vocab6',
    topicName: 'Bài 6: Finance & Expenses',
    cards: vocab6,
  );
  await _seedTopic(
    topicId: 'vocab7',
    topicName: 'Bài 7: Procurement & Inventory',
    cards: vocab7,
  );
  await _seedTopic(
    topicId: 'vocab8',
    topicName: 'Bài 8: Facilities & Maintenance',
    cards: vocab8,
  );
  await _seedTopic(
    topicId: 'vocab9',
    topicName: 'Bài 9: IT & Tech Support',
    cards: vocab9,
  );
  await _seedTopic(
    topicId: 'vocab10',
    topicName: 'Bài 10: Shipping & Delivery',
    cards: vocab10,
  );
}
