import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedVocabHard() async {
  final db = FirebaseFirestore.instance;
  const levelId = 'hard';

  Future<void> _seedTopic({
    required String topicId,
    required String topicName,
    required List<Map<String, String>> cards,
  }) async {
    await db
        .collection('vocab_cards')
        .doc(levelId)
        .collection('vocab_topics')
        .doc(topicId)
        .set({
          'topicName': topicName,
          'createdAt': FieldValue.serverTimestamp(),
        }, SetOptions(merge: true));

    for (int i = 0; i < cards.length; i++) {
      final id = 'q${(i + 1).toString().padLeft(2, '0')}';
      await db
          .collection('vocab_cards')
          .doc(levelId)
          .collection('vocab_topics')
          .doc(topicId)
          .collection('cards')
          .doc(id)
          .set(cards[i], SetOptions(merge: true));
    }
  }

  // Root doc
  await db.collection('vocab_cards').doc(levelId).set({
    'title': 'Vocabulary Level Hard',
    'vocabTopicId': [
      'vocab1',
      'vocab2',
      'vocab3',
      'vocab4',
      'vocab5',
      'vocab6',
      'vocab7',
      'vocab8',
      'vocab9',
      'vocab10',
    ],
    'createdAt': FieldValue.serverTimestamp(),
  }, SetOptions(merge: true));

  // =========================================================
  // Vocab 1: Reports & Data Insights (30 thẻ) — vocab1.pdf
  // =========================================================
  final vocab1 = <Map<String, String>>[
    {
      'word': 'trend',
      'phonetic': '/trend/',
      'meaningVi': 'xu hướng',
      'exampleEn': 'The sales trend is upward.',
      'exampleVi': 'Xu hướng doanh số đang tăng.',
    },
    {
      'word': 'variance',
      'phonetic': '/ˈveriəns/',
      'meaningVi': 'độ biến thiên/chênh lệch',
      'exampleEn': 'The variance is significant.',
      'exampleVi': 'Độ chênh lệch đáng kể.',
    },
    {
      'word': 'average',
      'phonetic': '/ˈævərɪdʒ/',
      'meaningVi': 'trung bình',
      'exampleEn': 'The average score rose.',
      'exampleVi': 'Điểm trung bình tăng.',
    },
    {
      'word': 'median',
      'phonetic': '/ˈmiːdiən/',
      'meaningVi': 'trung vị',
      'exampleEn': 'The median is stable.',
      'exampleVi': 'Trung vị ổn định.',
    },
    {
      'word': 'benchmark',
      'phonetic': '/ˈbentʃmɑːrk/',
      'meaningVi': 'chuẩn so sánh',
      'exampleEn': 'Set a new benchmark.',
      'exampleVi': 'Đặt chuẩn so sánh mới.',
    },
    {
      'word': 'metric',
      'phonetic': '/ˈmetrɪk/',
      'meaningVi': 'chỉ số đo lường',
      'exampleEn': 'Track key metrics.',
      'exampleVi': 'Theo dõi các chỉ số chính.',
    },
    {
      'word': 'KPI',
      'phonetic': '/ˌkeɪ piː ˈaɪ/',
      'meaningVi': 'chỉ số hiệu suất',
      'exampleEn': 'We defined three KPIs.',
      'exampleVi': 'Chúng tôi đã định nghĩa 3 KPI.',
    },
    {
      'word': 'insight',
      'phonetic': '/ˈɪnsaɪt/',
      'meaningVi': 'hiểu biết chuyên sâu',
      'exampleEn': 'Share your insights.',
      'exampleVi': 'Chia sẻ những insight của bạn.',
    },
    {
      'word': 'finding',
      'phonetic': '/ˈfaɪndɪŋ/',
      'meaningVi': 'kết quả phát hiện',
      'exampleEn': 'The findings are listed.',
      'exampleVi': 'Các kết quả được liệt kê.',
    },
    {
      'word': 'dataset',
      'phonetic': '/ˈdeɪtɑːset/',
      'meaningVi': 'bộ dữ liệu',
      'exampleEn': 'The dataset is large.',
      'exampleVi': 'Bộ dữ liệu rất lớn.',
    },
    {
      'word': 'sample',
      'phonetic': '/ˈsæmpl/',
      'meaningVi': 'mẫu',
      'exampleEn': 'We used a random sample.',
      'exampleVi': 'Chúng tôi dùng mẫu ngẫu nhiên.',
    },
    {
      'word': 'correlation',
      'phonetic': '/ˌkɔːrəˈleɪʃn/',
      'meaningVi': 'tương quan',
      'exampleEn': 'There’s a strong correlation.',
      'exampleVi': 'Có tương quan mạnh.',
    },
    {
      'word': 'increase',
      'phonetic': '/ɪnˈkriːs/',
      'meaningVi': 'tăng',
      'exampleEn': 'Sales increased by 8%.',
      'exampleVi': 'Doanh số tăng 8%.',
    },
    {
      'word': 'decrease',
      'phonetic': '/dɪˈkriːs/',
      'meaningVi': 'giảm',
      'exampleEn': 'Costs decreased slightly.',
      'exampleVi': 'Chi phí giảm nhẹ.',
    },
    {
      'word': 'fluctuate',
      'phonetic': '/ˈflʌktʃueɪt/',
      'meaningVi': 'dao động',
      'exampleEn': 'Prices fluctuated all year.',
      'exampleVi': 'Giá dao động cả năm.',
    },
    {
      'word': 'forecast',
      'phonetic': '/ˈfɔːrkæst/',
      'meaningVi': 'dự báo',
      'exampleEn': 'We forecast steady growth.',
      'exampleVi': 'Chúng tôi dự báo tăng trưởng ổn định.',
    },
    {
      'word': 'projection',
      'phonetic': '/prəˈdʒekʃn/',
      'meaningVi': 'dự phóng',
      'exampleEn': 'The projection is optimistic.',
      'exampleVi': 'Dự phóng lạc quan.',
    },
    {
      'word': 'growth rate',
      'phonetic': '/ɡroʊθ reɪt/',
      'meaningVi': 'tốc độ tăng trưởng',
      'exampleEn': 'The growth rate slowed.',
      'exampleVi': 'Tốc độ tăng trưởng chậm lại.',
    },
    {
      'word': 'pie chart',
      'phonetic': '/paɪ tʃɑːrt/',
      'meaningVi': 'biểu đồ tròn',
      'exampleEn': 'See the pie chart.',
      'exampleVi': 'Xem biểu đồ tròn.',
    },
    {
      'word': 'bar chart',
      'phonetic': '/bɑːr tʃɑːrt/',
      'meaningVi': 'biểu đồ cột',
      'exampleEn': 'The bar chart compares revenue.',
      'exampleVi': 'Biểu đồ cột so sánh doanh thu.',
    },
    {
      'word': 'line graph',
      'phonetic': '/laɪn ɡræf/',
      'meaningVi': 'đồ thị đường',
      'exampleEn': 'The line graph shows trends.',
      'exampleVi': 'Đồ thị đường thể hiện xu hướng.',
    },
    {
      'word': 'table',
      'phonetic': '/ˈteɪbl/',
      'meaningVi': 'bảng',
      'exampleEn': 'Refer to Table 2.',
      'exampleVi': 'Tham chiếu Bảng 2.',
    },
    {
      'word': 'figure',
      'phonetic': '/ˈfɪɡjər/',
      'meaningVi': 'hình/đồ thị',
      'exampleEn': 'See Figure 4.',
      'exampleVi': 'Xem Hình 4.',
    },
    {
      'word': 'appendix',
      'phonetic': '/əˈpendɪks/',
      'meaningVi': 'phụ lục',
      'exampleEn': 'Data is in the appendix.',
      'exampleVi': 'Dữ liệu ở phụ lục.',
    },
    {
      'word': 'interpretation',
      'phonetic': '/ɪnˌtɜːrprɪˈteɪʃn/',
      'meaningVi': 'diễn giải',
      'exampleEn': 'Provide an interpretation.',
      'exampleVi': 'Cung cấp phần diễn giải.',
    },
    {
      'word': 'implication',
      'phonetic': '/ˌɪmplɪˈkeɪʃn/',
      'meaningVi': 'hàm ý',
      'exampleEn': 'Business implications are clear.',
      'exampleVi': 'Hàm ý kinh doanh rõ ràng.',
    },
    {
      'word': 'summary',
      'phonetic': '/ˈsʌməri/',
      'meaningVi': 'tóm tắt',
      'exampleEn': 'Write a short summary.',
      'exampleVi': 'Viết bản tóm tắt ngắn.',
    },
    {
      'word': 'executive summary',
      'phonetic': '/ɪɡˈzekjətɪv ˈsʌməri/',
      'meaningVi': 'tóm tắt điều hành',
      'exampleEn': 'Add an executive summary.',
      'exampleVi': 'Thêm phần tóm tắt điều hành.',
    },
    {
      'word': 'highlight',
      'phonetic': '/ˈhaɪlaɪt/',
      'meaningVi': 'điểm nhấn; làm nổi bật',
      'exampleEn': 'Highlight key results.',
      'exampleVi': 'Làm nổi bật kết quả chính.',
    },
    {
      'word': 'anomaly',
      'phonetic': '/əˈnɒməli/',
      'meaningVi': 'bất thường',
      'exampleEn': 'We found an anomaly.',
      'exampleVi': 'Chúng tôi phát hiện điểm bất thường.',
    },
  ];

  // =========================================================
  // Vocab 2: Budgeting & Forecasting (30 thẻ) — vocab2.pdf
  // =========================================================
  final vocab2 = <Map<String, String>>[
    {
      'word': 'budget',
      'phonetic': '/ˈbʌdʒɪt/',
      'meaningVi': 'ngân sách; lập ngân sách',
      'exampleEn': 'We set the annual budget.',
      'exampleVi': 'Chúng tôi đặt ngân sách năm.',
    },
    {
      'word': 'allocate',
      'phonetic': '/ˈæləkeɪt/',
      'meaningVi': 'phân bổ',
      'exampleEn': 'Allocate funds wisely.',
      'exampleVi': 'Phân bổ quỹ khôn ngoan.',
    },
    {
      'word': 'expenditure',
      'phonetic': '/ɪkˈspendɪtʃər/',
      'meaningVi': 'chi tiêu',
      'exampleEn': 'Cut unnecessary expenditure.',
      'exampleVi': 'Cắt chi tiêu không cần thiết.',
    },
    {
      'word': 'revenue',
      'phonetic': '/ˈrevənjuː/',
      'meaningVi': 'doanh thu',
      'exampleEn': 'Revenue increased 10%.',
      'exampleVi': 'Doanh thu tăng 10%.',
    },
    {
      'word': 'cost',
      'phonetic': '/kɔːst/',
      'meaningVi': 'chi phí',
      'exampleEn': 'Reduce operating costs.',
      'exampleVi': 'Giảm chi phí vận hành.',
    },
    {
      'word': 'expense',
      'phonetic': '/ɪkˈspens/',
      'meaningVi': 'khoản chi',
      'exampleEn': 'Track travel expenses.',
      'exampleVi': 'Theo dõi chi phí đi lại.',
    },
    {
      'word': 'overhead',
      'phonetic': '/ˈoʊvərhed/',
      'meaningVi': 'chi phí cố định',
      'exampleEn': 'Lower overhead this quarter.',
      'exampleVi': 'Giảm chi phí cố định quý này.',
    },
    {
      'word': 'fiscal year',
      'phonetic': '/ˈfɪskl jɪr/',
      'meaningVi': 'năm tài chính',
      'exampleEn': 'Our fiscal year ends in June.',
      'exampleVi': 'Năm tài chính kết thúc tháng 6.',
    },
    {
      'word': 'quarter',
      'phonetic': '/ˈkwɔːrtər/',
      'meaningVi': 'quý',
      'exampleEn': 'Results for the third quarter.',
      'exampleVi': 'Kết quả quý ba.',
    },
    {
      'word': 'projection',
      'phonetic': '/prəˈdʒekʃn/',
      'meaningVi': 'dự phóng',
      'exampleEn': 'Sales projections look strong.',
      'exampleVi': 'Dự phóng doanh số tích cực.',
    },
    {
      'word': 'estimate',
      'phonetic': '/ˈestɪmət/',
      'meaningVi': 'ước tính; ước lượng',
      'exampleEn': 'Provide a cost estimate.',
      'exampleVi': 'Cung cấp ước tính chi phí.',
    },
    {
      'word': 'assumption',
      'phonetic': '/əˈsʌmpʃn/',
      'meaningVi': 'giả định',
      'exampleEn': 'State all assumptions.',
      'exampleVi': 'Nêu mọi giả định.',
    },
    {
      'word': 'contingency',
      'phonetic': '/kənˈtɪndʒənsi/',
      'meaningVi': 'dự phòng',
      'exampleEn': 'Add a contingency fund.',
      'exampleVi': 'Thêm quỹ dự phòng.',
    },
    {
      'word': 'surplus',
      'phonetic': '/ˈsɜːrplʌs/',
      'meaningVi': 'thặng dư',
      'exampleEn': 'We have a budget surplus.',
      'exampleVi': 'Ta có thặng dư ngân sách.',
    },
    {
      'word': 'deficit',
      'phonetic': '/ˈdefɪsɪt/',
      'meaningVi': 'thâm hụt',
      'exampleEn': 'The deficit narrowed.',
      'exampleVi': 'Thâm hụt đã thu hẹp.',
    },
    {
      'word': 'cash flow',
      'phonetic': '/ˈkæʃ floʊ/',
      'meaningVi': 'dòng tiền',
      'exampleEn': 'Monitor cash flow weekly.',
      'exampleVi': 'Theo dõi dòng tiền hàng tuần.',
    },
    {
      'word': 'break-even',
      'phonetic': '/breɪk ˈiːvn/',
      'meaningVi': 'hòa vốn',
      'exampleEn': 'Reach break-even by Q4.',
      'exampleVi': 'Hòa vốn vào quý 4.',
    },
    {
      'word': 'ROI',
      'phonetic': '/ˌɑːr oʊ ˈaɪ/',
      'meaningVi': 'lợi tức đầu tư',
      'exampleEn': 'Target a 20% ROI.',
      'exampleVi': 'Mục tiêu ROI 20%.',
    },
    {
      'word': 'margin',
      'phonetic': '/ˈmɑːrdʒɪn/',
      'meaningVi': 'biên lợi nhuận',
      'exampleEn': 'Improve profit margins.',
      'exampleVi': 'Cải thiện biên lợi nhuận.',
    },
    {
      'word': 'gross',
      'phonetic': '/ɡroʊs/',
      'meaningVi': 'gộp, trước khấu trừ',
      'exampleEn': 'Gross profit rose.',
      'exampleVi': 'Lợi nhuận gộp tăng.',
    },
    {
      'word': 'net',
      'phonetic': '/net/',
      'meaningVi': 'ròng, sau khấu trừ',
      'exampleEn': 'Net income fell.',
      'exampleVi': 'Thu nhập ròng giảm.',
    },
    {
      'word': 'balance',
      'phonetic': '/ˈbæl.əns/',
      'meaningVi': 'số dư/cân đối',
      'exampleEn': 'Keep a positive balance.',
      'exampleVi': 'Giữ số dư dương.',
    },
    {
      'word': 'variance',
      'phonetic': '/ˈveriəns/',
      'meaningVi': 'chênh lệch',
      'exampleEn': 'Explain the variance.',
      'exampleVi': 'Giải thích chênh lệch.',
    },
    {
      'word': 'revise',
      'phonetic': '/rɪˈvaɪz/',
      'meaningVi': 'điều chỉnh',
      'exampleEn': 'Revise the forecast.',
      'exampleVi': 'Điều chỉnh dự báo.',
    },
    {
      'word': 'approval',
      'phonetic': '/əˈpruːvl/',
      'meaningVi': 'phê duyệt',
      'exampleEn': 'Awaiting budget approval.',
      'exampleVi': 'Đang chờ phê duyệt ngân sách.',
    },
    {
      'word': 'capital',
      'phonetic': '/ˈkæpɪtl/',
      'meaningVi': 'vốn',
      'exampleEn': 'Raise more capital.',
      'exampleVi': 'Huy động thêm vốn.',
    },
    {
      'word': 'operating costs',
      'phonetic': '/ˈɒpəreɪtɪŋ kɒsts/',
      'meaningVi': 'chi phí vận hành',
      'exampleEn': 'Cut operating costs by 5%.',
      'exampleVi': 'Giảm chi phí vận hành 5%.',
    },
    {
      'word': 'depreciation',
      'phonetic': '/dɪˌpriːʃiˈeɪʃn/',
      'meaningVi': 'khấu hao',
      'exampleEn': 'Record annual depreciation.',
      'exampleVi': 'Ghi nhận khấu hao hằng năm.',
    },
    {
      'word': 'forecast',
      'phonetic': '/ˈfɔːrkæst/',
      'meaningVi': 'dự báo',
      'exampleEn': 'Forecast expenses monthly.',
      'exampleVi': 'Dự báo chi phí hàng tháng.',
    },
    {
      'word': 'baseline',
      'phonetic': '/ˈbeɪslaɪn/',
      'meaningVi': 'đường cơ sở',
      'exampleEn': 'Set a baseline for costs.',
      'exampleVi': 'Đặt đường cơ sở cho chi phí.',
    },
  ];

  // =========================================================
  // Vocab 3: Contracts & Legal Terms (30 thẻ) — vocab3.pdf
  // =========================================================
  final vocab3 = <Map<String, String>>[
    {
      'word': 'clause',
      'phonetic': '/klɔːz/',
      'meaningVi': 'điều khoản',
      'exampleEn': 'This clause limits liability.',
      'exampleVi': 'Điều khoản này giới hạn trách nhiệm.',
    },
    {
      'word': 'liability',
      'phonetic': '/ˌlaɪəˈbɪləti/',
      'meaningVi': 'trách nhiệm pháp lý',
      'exampleEn': 'The company accepts liability.',
      'exampleVi': 'Công ty chấp nhận trách nhiệm pháp lý.',
    },
    {
      'word': 'indemnify',
      'phonetic': '/ɪnˈdɛm nɪfaɪ/',
      'meaningVi': 'bồi thường',
      'exampleEn': 'We agree to indemnify the client.',
      'exampleVi': 'Chúng tôi đồng ý bồi thường cho khách hàng.',
    },
    {
      'word': 'indemnity',
      'phonetic': '/ɪnˈdɛm nɪti/',
      'meaningVi': 'khoản bồi thường',
      'exampleEn': 'An indemnity is included.',
      'exampleVi': 'Có kèm một khoản bồi thường.',
    },
    {
      'word': 'warranty',
      'phonetic': '/ˈwɒrən ti/',
      'meaningVi': 'bảo hành',
      'exampleEn': 'A one-year warranty applies.',
      'exampleVi': 'Áp dụng bảo hành một năm.',
    },
    {
      'word': 'representation',
      'phonetic': '/ˌrɛprɪzɛnˈteɪʃən/',
      'meaningVi': 'lời cam đoan',
      'exampleEn': 'Her representation was accurate.',
      'exampleVi': 'Lời cam đoan của cô ấy chính xác.',
    },
    {
      'word': 'covenant',
      'phonetic': '/ˈkʌvənənt/',
      'meaningVi': 'cam kết (ràng buộc)',
      'exampleEn': 'This covenant forbids resale.',
      'exampleVi': 'Cam kết này cấm bán lại.',
    },
    {
      'word': 'breach',
      'phonetic': '/briːtʃ/',
      'meaningVi': 'vi phạm',
      'exampleEn': 'They are in breach of contract.',
      'exampleVi': 'Họ đang vi phạm hợp đồng.',
    },
    {
      'word': 'terminate',
      'phonetic': '/ˈtɜːmɪneɪt/',
      'meaningVi': 'chấm dứt',
      'exampleEn': 'Either party may terminate.',
      'exampleVi': 'Bên nào cũng có thể chấm dứt.',
    },
    {
      'word': 'termination',
      'phonetic': '/ˌtɜːmɪˈneɪʃn/',
      'meaningVi': 'sự chấm dứt',
      'exampleEn': 'Termination occurs after notice.',
      'exampleVi': 'Việc chấm dứt diễn ra sau thông báo.',
    },
    {
      'word': 'renew',
      'phonetic': '/rɪˈnjuː/',
      'meaningVi': 'gia hạn',
      'exampleEn': 'We will renew the agreement.',
      'exampleVi': 'Chúng tôi sẽ gia hạn thỏa thuận.',
    },
    {
      'word': 'renewal',
      'phonetic': '/rɪˈnjuːəl/',
      'meaningVi': 'việc gia hạn',
      'exampleEn': 'Automatic renewal every year.',
      'exampleVi': 'Tự động gia hạn hằng năm.',
    },
    {
      'word': 'assignment',
      'phonetic': '/əˈsaɪnmənt/',
      'meaningVi': 'chuyển nhượng',
      'exampleEn': 'Assignment needs consent.',
      'exampleVi': 'Chuyển nhượng cần có chấp thuận.',
    },
    {
      'word': 'governing law',
      'phonetic': '/ˈɡʌvənɪŋ lɔː/',
      'meaningVi': 'luật điều chỉnh',
      'exampleEn': 'The governing law is NY.',
      'exampleVi': 'Luật điều chỉnh là của NY.',
    },
    {
      'word': 'jurisdiction',
      'phonetic': '/ˌdʒʊərɪsˈdɪkʃən/',
      'meaningVi': 'thẩm quyền',
      'exampleEn': 'Courts have exclusive jurisdiction.',
      'exampleVi': 'Tòa án có thẩm quyền riêng.',
    },
    {
      'word': 'force majeure',
      'phonetic': '/ˌfɔːs mæˈʒɜː/',
      'meaningVi': 'bất khả kháng',
      'exampleEn': 'Force majeure covers strikes.',
      'exampleVi': 'Điều khoản bất khả kháng bao gồm đình công.',
    },
    {
      'word': 'confidentiality',
      'phonetic': '/ˌkɒn fɪˌdenʃiˈælɪti/',
      'meaningVi': 'bảo mật',
      'exampleEn': 'Confidentiality is required.',
      'exampleVi': 'Yêu cầu bảo mật.',
    },
    {
      'word': 'non-disclosure',
      'phonetic': '/ˌnɒn dɪˈskloʊʒər/',
      'meaningVi': 'không tiết lộ',
      'exampleEn': 'Sign a non-disclosure agreement.',
      'exampleVi': 'Ký thỏa thuận không tiết lộ.',
    },
    {
      'word': 'non-compete',
      'phonetic': '/ˌnɒn kəmˈpiːt/',
      'meaningVi': 'không cạnh tranh',
      'exampleEn': 'He signed a non-compete.',
      'exampleVi': 'Anh ấy đã ký điều khoản không cạnh tranh.',
    },
    {
      'word': 'consideration',
      'phonetic': '/kənˌsɪdəˈreɪʃən/',
      'meaningVi': 'đối giá (giá trị trao đổi)',
      'exampleEn': 'Consideration is clearly stated.',
      'exampleVi': 'Đối giá được nêu rõ.',
    },
    {
      'word': 'counterpart',
      'phonetic': '/ˈkaʊntəpɑːt/',
      'meaningVi': 'bản ký tương ứng',
      'exampleEn': 'Sign in two counterparts.',
      'exampleVi': 'Ký thành hai bản tương ứng.',
    },
    {
      'word': 'severability',
      'phonetic': '/ˌsɛvərəˈbɪləti/',
      'meaningVi': 'tính tách biệt điều khoản',
      'exampleEn': 'Severability protects the rest.',
      'exampleVi': 'Tính tách biệt bảo vệ phần còn lại.',
    },
    {
      'word': 'entire agreement',
      'phonetic': '/ɪnˈtaɪər əˈɡriːmənt/',
      'meaningVi': 'toàn bộ thỏa thuận',
      'exampleEn': 'This is the entire agreement.',
      'exampleVi': 'Đây là toàn bộ thỏa thuận.',
    },
    {
      'word': 'amend',
      'phonetic': '/əˈmɛnd/',
      'meaningVi': 'sửa đổi',
      'exampleEn': 'The parties may amend the contract.',
      'exampleVi': 'Các bên có thể sửa đổi hợp đồng.',
    },
    {
      'word': 'amendment',
      'phonetic': '/əˈmɛndmənt/',
      'meaningVi': 'bản sửa đổi',
      'exampleEn': 'An amendment was issued.',
      'exampleVi': 'Đã ban hành bản sửa đổi.',
    },
    {
      'word': 'dispute',
      'phonetic': '/dɪˈspjuːt/',
      'meaningVi': 'tranh chấp',
      'exampleEn': 'Settle disputes by arbitration.',
      'exampleVi': 'Giải quyết tranh chấp bằng trọng tài.',
    },
    {
      'word': 'arbitration',
      'phonetic': '/ˌɑːbɪˈtreɪʃən/',
      'meaningVi': 'trọng tài',
      'exampleEn': 'Arbitration is binding.',
      'exampleVi': 'Trọng tài có hiệu lực ràng buộc.',
    },
    {
      'word': 'mediation',
      'phonetic': '/ˌmiːdiˈeɪʃən/',
      'meaningVi': 'hòa giải',
      'exampleEn': 'Mediation occurs first.',
      'exampleVi': 'Hòa giải diễn ra trước.',
    },
    {
      'word': 'remedy',
      'phonetic': '/ˈrɛmɪdi/',
      'meaningVi': 'biện pháp khắc phục',
      'exampleEn': 'Injunction is a remedy.',
      'exampleVi': 'Lệnh cấm là một biện pháp khắc phục.',
    },
    {
      'word': 'liquidated damages',
      'phonetic': '/ˌlɪkwɪdeɪtɪd ˈdæmɪdʒɪz/',
      'meaningVi': 'tiền phạt định trước',
      'exampleEn': 'Liquidated damages apply for delays.',
      'exampleVi': 'Áp dụng tiền phạt định trước nếu chậm trễ.',
    },
  ];

  // =========================================================
  // Vocab 4: Procurement Advanced (30 thẻ) — vocab4.pdf
  // =========================================================
  final vocab4 = <Map<String, String>>[
    {
      'word': 'vendor evaluation',
      'phonetic': '/ˈvɛndər ˌiːvæljuˈeɪʃən/',
      'meaningVi': 'đánh giá nhà bán',
      'exampleEn': 'We finished vendor evaluation.',
      'exampleVi': 'Chúng tôi đã hoàn tất đánh giá nhà bán.',
    },
    {
      'word': 'supplier shortlist',
      'phonetic': '/səˈplaɪər ˈʃɔːtlɪst/',
      'meaningVi': 'danh sách rút gọn NCC',
      'exampleEn': 'Create a supplier shortlist.',
      'exampleVi': 'Tạo danh sách NCC rút gọn.',
    },
    {
      'word': 'prequalification',
      'phonetic': '/ˌpriːˌkwɒlɪfɪˈkeɪʃn/',
      'meaningVi': 'tiền thẩm định',
      'exampleEn': 'Run prequalification checks.',
      'exampleVi': 'Thực hiện kiểm tra tiền thẩm định.',
    },
    {
      'word': 'technical specification',
      'phonetic': '/ˈtɛknɪkəl ˌspɛsɪfɪˈkeɪʃn/',
      'meaningVi': 'thông số kỹ thuật',
      'exampleEn': 'Provide technical specifications.',
      'exampleVi': 'Cung cấp thông số kỹ thuật.',
    },
    {
      'word': 'commercial terms',
      'phonetic': '/kəˈmɜːʃəl tɜːmz/',
      'meaningVi': 'điều khoản thương mại',
      'exampleEn': 'Negotiate commercial terms.',
      'exampleVi': 'Đàm phán điều khoản thương mại.',
    },
    {
      'word': 'incoterms',
      'phonetic': '/ˈɪŋkoʊtɜːmz/',
      'meaningVi': 'điều kiện thương mại quốc tế',
      'exampleEn': 'Select suitable Incoterms.',
      'exampleVi': 'Chọn Incoterms phù hợp.',
    },
    {
      'word': 'FOB',
      'phonetic': '/ˌɛf oʊ ˈbiː/',
      'meaningVi': 'Giao lên tàu (FOB)',
      'exampleEn': 'Price is quoted FOB Hanoi.',
      'exampleVi': 'Giá báo theo điều kiện FOB Hà Nội.',
    },
    {
      'word': 'CIF',
      'phonetic': '/ˌsiː aɪ ˈɛf/',
      'meaningVi': 'Giá CIF',
      'exampleEn': 'Offer includes CIF charges.',
      'exampleVi': 'Báo giá bao gồm chi phí CIF.',
    },
    {
      'word': 'bid bond',
      'phonetic': '/bɪd bɒnd/',
      'meaningVi': 'bảo lãnh dự thầu',
      'exampleEn': 'Submit a bid bond.',
      'exampleVi': 'Nộp bảo lãnh dự thầu.',
    },
    {
      'word': 'performance bond',
      'phonetic': '/pəˈfɔːməns bɒnd/',
      'meaningVi': 'bảo lãnh thực hiện',
      'exampleEn': 'A performance bond is required.',
      'exampleVi': 'Cần bảo lãnh thực hiện.',
    },
    {
      'word': 'liquidated damages',
      'phonetic': '/ˌlɪkwɪdeɪtɪd ˈdæmɪdʒɪz/',
      'meaningVi': 'phạt vi phạm tiến độ',
      'exampleEn': 'LDs apply for delays.',
      'exampleVi': 'Áp dụng phạt nếu chậm tiến độ.',
    },
    {
      'word': 'service level agreement',
      'phonetic': '/ˌsɜːvɪs ˈlɛvəl əˈgriːmənt/',
      'meaningVi': 'thỏa thuận mức dịch vụ (SLA)',
      'exampleEn': 'The SLA defines uptime.',
      'exampleVi': 'SLA quy định thời gian hoạt động.',
    },
    {
      'word': 'penalty',
      'phonetic': '/ˈpɛnəlti/',
      'meaningVi': 'tiền phạt',
      'exampleEn': 'A penalty schedule is attached.',
      'exampleVi': 'Kèm bảng phạt.',
    },
    {
      'word': 'deliverable',
      'phonetic': '/dɪˈlɪvərəbl/',
      'meaningVi': 'hạng mục giao hàng',
      'exampleEn': 'List all deliverables.',
      'exampleVi': 'Liệt kê mọi hạng mục giao.',
    },
    {
      'word': 'milestone payment',
      'phonetic': '/ˈmaɪlstoʊn ˈpeɪmənt/',
      'meaningVi': 'thanh toán theo mốc',
      'exampleEn': 'Use milestone payments.',
      'exampleVi': 'Dùng thanh toán theo mốc.',
    },
    {
      'word': 'change order',
      'phonetic': '/tʃeɪndʒ ˈɔːrdər/',
      'meaningVi': 'lệnh thay đổi',
      'exampleEn': 'Approve a change order.',
      'exampleVi': 'Phê duyệt lệnh thay đổi.',
    },
    {
      'word': 'acceptance test',
      'phonetic': '/əkˈsɛptəns tɛst/',
      'meaningVi': 'kiểm tra nghiệm thu',
      'exampleEn': 'Schedule acceptance tests.',
      'exampleVi': 'Lên lịch kiểm tra nghiệm thu.',
    },
    {
      'word': 'handover',
      'phonetic': '/ˈhændˌoʊvər/',
      'meaningVi': 'bàn giao',
      'exampleEn': 'Handover is next week.',
      'exampleVi': 'Bàn giao vào tuần tới.',
    },
    {
      'word': 'service window',
      'phonetic': '/ˈsɜːrvɪs ˈwɪndoʊ/',
      'meaningVi': 'khung giờ dịch vụ',
      'exampleEn': 'Set a service window.',
      'exampleVi': 'Đặt khung giờ dịch vụ.',
    },
    {
      'word': 'escalation',
      'phonetic': '/ˌɛskəˈleɪʃən/',
      'meaningVi': 'leo thang xử lý',
      'exampleEn': 'Define an escalation path.',
      'exampleVi': 'Định nghĩa lộ trình leo thang.',
    },
    {
      'word': 'vendor lock-in',
      'phonetic': '/ˈvɛndər lɒk ɪn/',
      'meaningVi': 'khóa nhà cung cấp',
      'exampleEn': 'Avoid vendor lock-in.',
      'exampleVi': 'Tránh phụ thuộc một nhà cung cấp.',
    },
    {
      'word': 'dual sourcing',
      'phonetic': '/ˌdjuːəl ˈsɔːsɪŋ/',
      'meaningVi': 'mua từ 2 nguồn',
      'exampleEn': 'Adopt dual sourcing.',
      'exampleVi': 'Áp dụng mua từ hai nguồn.',
    },
    {
      'word': 'benchmarking',
      'phonetic': '/ˈbɛntʃmɑːrkɪŋ/',
      'meaningVi': 'so sánh chuẩn',
      'exampleEn': 'Do price benchmarking.',
      'exampleVi': 'Thực hiện so sánh giá chuẩn.',
    },
    {
      'word': 'total cost of ownership',
      'phonetic': '/ˈtoʊtl kɒst əv ˈoʊnərʃɪp/',
      'meaningVi': 'tổng chi phí sở hữu (TCO)',
      'exampleEn': 'Calculate TCO over 3 years.',
      'exampleVi': 'Tính TCO trong 3 năm.',
    },
    {
      'word': 'request for information',
      'phonetic': '/rɪˈkwɛst fɔːr ɪnfəˈmeɪʃən/',
      'meaningVi': 'yêu cầu thông tin (RFI)',
      'exampleEn': 'Send an RFI first.',
      'exampleVi': 'Gửi RFI trước.',
    },
    {
      'word': 'vendor onboarding',
      'phonetic': '/ˈvɛndər ˈɒnbɔːrdɪŋ/',
      'meaningVi': 'kết nạp nhà bán',
      'exampleEn': 'Speed up vendor onboarding.',
      'exampleVi': 'Tăng tốc kết nạp nhà bán.',
    },
    {
      'word': 'SLAs & KPIs',
      'phonetic': '/ˌɛs ɛl ˈeɪz ænd ˌkeɪ piː ˈaɪz/',
      'meaningVi': 'SLA & KPI',
      'exampleEn': 'SLAs and KPIs are measurable.',
      'exampleVi': 'SLA và KPI có thể đo lường.',
    },
    {
      'word': 'framework agreement',
      'phonetic': '/ˈfreɪmwɜːrk əˈgriːmənt/',
      'meaningVi': 'thỏa thuận khung',
      'exampleEn': 'Sign a framework agreement.',
      'exampleVi': 'Ký thỏa thuận khung.',
    },
    {
      'word': 'call-off order',
      'phonetic': '/kɔːl ɒf ˈɔːrdər/',
      'meaningVi': 'đơn đặt theo khung',
      'exampleEn': 'Issue call-off orders monthly.',
      'exampleVi': 'Phát hành đơn đặt theo khung hàng tháng.',
    },
    {
      'word': 'price adjustment',
      'phonetic': '/praɪs ədˈʤʌstmənt/',
      'meaningVi': 'điều chỉnh giá',
      'exampleEn': 'Include a price adjustment clause.',
      'exampleVi': 'Bao gồm điều khoản điều chỉnh giá.',
    },
  ];

  // =========================================================
  // Vocab 5: Quality & Audits (30 thẻ) — vocab5.pdf
  // =========================================================
  final vocab5 = <Map<String, String>>[
    {
      'word': 'quality standard',
      'phonetic': '/ˈkwɒləti ˈstændəd/',
      'meaningVi': 'tiêu chuẩn chất lượng',
      'exampleEn': 'Meet the quality standard.',
      'exampleVi': 'Đáp ứng tiêu chuẩn chất lượng.',
    },
    {
      'word': 'specification',
      'phonetic': '/ˌspɛsɪfɪˈkeɪʃən/',
      'meaningVi': 'thông số kỹ thuật',
      'exampleEn': 'Follow the specification.',
      'exampleVi': 'Tuân theo thông số.',
    },
    {
      'word': 'tolerance',
      'phonetic': '/ˈtɒlərəns/',
      'meaningVi': 'dung sai',
      'exampleEn': 'The tolerance is ±0.2 mm.',
      'exampleVi': 'Dung sai là ±0,2 mm.',
    },
    {
      'word': 'defect',
      'phonetic': '/ˈdiːfekt/',
      'meaningVi': 'lỗi',
      'exampleEn': 'We found a minor defect.',
      'exampleVi': 'Chúng tôi phát hiện lỗi nhỏ.',
    },
    {
      'word': 'nonconformity',
      'phonetic': '/ˌnɒnkənˈfɔːməti/',
      'meaningVi': 'không phù hợp',
      'exampleEn': 'Record the nonconformity.',
      'exampleVi': 'Ghi nhận điểm không phù hợp.',
    },
    {
      'word': 'root cause',
      'phonetic': '/ruːt kɔːz/',
      'meaningVi': 'nguyên nhân gốc',
      'exampleEn': 'Analyze the root cause.',
      'exampleVi': 'Phân tích nguyên nhân gốc.',
    },
    {
      'word': 'CAPA',
      'phonetic': '/ˌsiː eɪ piː eɪ/',
      'meaningVi': 'hành động khắc phục & phòng ngừa',
      'exampleEn': 'Implement CAPA actions.',
      'exampleVi': 'Triển khai hành động CAPA.',
    },
    {
      'word': 'inspection',
      'phonetic': '/ɪnˈspɛkʃən/',
      'meaningVi': 'kiểm tra',
      'exampleEn': 'Do incoming inspection.',
      'exampleVi': 'Thực hiện kiểm tra đầu vào.',
    },
    {
      'word': 'sampling',
      'phonetic': '/ˈsæmplɪŋ/',
      'meaningVi': 'lấy mẫu',
      'exampleEn': 'Use random sampling.',
      'exampleVi': 'Dùng phương pháp lấy mẫu ngẫu nhiên.',
    },
    {
      'word': 'batch',
      'phonetic': '/bætʃ/',
      'meaningVi': 'lô',
      'exampleEn': 'Approve the batch.',
      'exampleVi': 'Phê duyệt lô hàng.',
    },
    {
      'word': 'audit',
      'phonetic': '/ˈɔːdɪt/',
      'meaningVi': 'đánh giá/kiểm toán',
      'exampleEn': 'Schedule an internal audit.',
      'exampleVi': 'Lên lịch đánh giá nội bộ.',
    },
    {
      'word': 'auditor',
      'phonetic': '/ˈɔːdɪtər/',
      'meaningVi': 'kiểm toán viên',
      'exampleEn': 'External auditors will visit.',
      'exampleVi': 'Kiểm toán viên bên ngoài sẽ đến.',
    },
    {
      'word': 'certification',
      'phonetic': '/ˌsɜːtɪfɪˈkeɪʃən/',
      'meaningVi': 'chứng nhận',
      'exampleEn': 'ISO certification is required.',
      'exampleVi': 'Cần chứng nhận ISO.',
    },
    {
      'word': 'compliance',
      'phonetic': '/kəmˈplaɪəns/',
      'meaningVi': 'tuân thủ',
      'exampleEn': 'Ensure compliance with ISO 9001.',
      'exampleVi': 'Đảm bảo tuân thủ ISO 9001.',
    },
    {
      'word': 'procedures',
      'phonetic': '/prəˈsiːdʒərz/',
      'meaningVi': 'quy trình',
      'exampleEn': 'Document all procedures.',
      'exampleVi': 'Ghi chép tất cả quy trình.',
    },
    {
      'word': 'work instruction',
      'phonetic': '/wɜːk ɪnˈstrʌkʃən/',
      'meaningVi': 'hướng dẫn công việc',
      'exampleEn': 'Update work instructions.',
      'exampleVi': 'Cập nhật hướng dẫn công việc.',
    },
    {
      'word': 'checklist',
      'phonetic': '/ˈtʃɛklɪst/',
      'meaningVi': 'danh sách kiểm',
      'exampleEn': 'Use a checklist for audits.',
      'exampleVi': 'Dùng danh sách kiểm cho đánh giá.',
    },
    {
      'word': 'traceability',
      'phonetic': '/ˌtreɪsəˈbɪlɪti/',
      'meaningVi': 'truy xuất nguồn gốc',
      'exampleEn': 'Maintain traceability records.',
      'exampleVi': 'Duy trì hồ sơ truy xuất.',
    },
    {
      'word': 'calibration',
      'phonetic': '/ˌkælɪˈbreɪʃən/',
      'meaningVi': 'hiệu chuẩn',
      'exampleEn': 'Calibration is overdue.',
      'exampleVi': 'Hiệu chuẩn đã quá hạn.',
    },
    {
      'word': 'specimen',
      'phonetic': '/ˈspɛsɪmən/',
      'meaningVi': 'mẫu thử',
      'exampleEn': 'Test the specimen.',
      'exampleVi': 'Kiểm tra mẫu thử.',
    },
    {
      'word': 'benchmark',
      'phonetic': '/ˈbɛntʃmɑːrk/',
      'meaningVi': 'chuẩn so sánh; so sánh',
      'exampleEn': 'Benchmark against peers.',
      'exampleVi': 'So sánh với các bên cùng ngành.',
    },
    {
      'word': 'continuous improvement',
      'phonetic': '/kənˈtɪnjʊəs ɪmˈpruːvmənt/',
      'meaningVi': 'cải tiến liên tục',
      'exampleEn': 'Pursue continuous improvement.',
      'exampleVi': 'Theo đuổi cải tiến liên tục.',
    },
    {
      'word': 'quality gate',
      'phonetic': '/ˈkwɒləti ɡeɪt/',
      'meaningVi': 'cổng chất lượng',
      'exampleEn': 'Add a quality gate before shipping.',
      'exampleVi': 'Thêm cổng chất lượng trước khi giao.',
    },
    {
      'word': 'acceptance criteria',
      'phonetic': '/əkˈsɛptəns kraɪˈtɪəriə/',
      'meaningVi': 'tiêu chí chấp nhận',
      'exampleEn': 'Define acceptance criteria.',
      'exampleVi': 'Định nghĩa tiêu chí chấp nhận.',
    },
    {
      'word': 'deviation',
      'phonetic': '/ˌdiːviˈeɪʃən/',
      'meaningVi': 'độ lệch',
      'exampleEn': 'Approve a deviation form.',
      'exampleVi': 'Phê duyệt biểu mẫu độ lệch.',
    },
    {
      'word': 'waiver',
      'phonetic': '/ˈweɪvər/',
      'meaningVi': 'miễn trừ',
      'exampleEn': 'Request a waiver.',
      'exampleVi': 'Yêu cầu miễn trừ.',
    },
    {
      'word': 'risk register',
      'phonetic': '/rɪsk ˈrɛdʒɪstər/',
      'meaningVi': 'sổ đăng ký rủi ro',
      'exampleEn': 'Update the risk register.',
      'exampleVi': 'Cập nhật sổ rủi ro.',
    },
    {
      'word': 'audit trail',
      'phonetic': '/ˈɔːdɪt treɪl/',
      'meaningVi': 'vết kiểm toán',
      'exampleEn': 'Keep a full audit trail.',
      'exampleVi': 'Giữ đầy đủ vết kiểm toán.',
    },
    {
      'word': 'non-destructive testing',
      'phonetic': '/ˌnɒn dɪˈstrʌktɪv ˈtɛstɪŋ/',
      'meaningVi': 'thử nghiệm không phá hủy',
      'exampleEn': 'Use non-destructive testing.',
      'exampleVi': 'Dùng thử nghiệm không phá hủy.',
    },
    {
      'word': 'gauge R&R',
      'phonetic': '/ɡeɪdʒ ɑːr ænd ɑːr/',
      'meaningVi': 'độ lặp lại & tái lập phép đo',
      'exampleEn': 'Run a gauge R&R study.',
      'exampleVi': 'Chạy nghiên cứu gauge R&R.',
    },
  ];

  // =========================================================
  // Vocab 6: Corporate Strategy & Change (30 thẻ) — vocab6.pdf
  // =========================================================
  final vocab6 = <Map<String, String>>[
    {
      'word': 'initiative',
      'phonetic': '/ɪˈnɪʃətɪv/',
      'meaningVi': 'sáng kiến',
      'exampleEn': 'Launch a cost-saving initiative.',
      'exampleVi': 'Ra mắt sáng kiến tiết kiệm chi phí.',
    },
    {
      'word': 'roadmap',
      'phonetic': '/ˈroʊdmæp/',
      'meaningVi': 'lộ trình',
      'exampleEn': 'Publish the product roadmap.',
      'exampleVi': 'Công bố lộ trình sản phẩm.',
    },
    {
      'word': 'objective',
      'phonetic': '/əbˈdʒɛktɪv/',
      'meaningVi': 'mục tiêu',
      'exampleEn': 'Set clear objectives.',
      'exampleVi': 'Đặt mục tiêu rõ ràng.',
    },
    {
      'word': 'OKR',
      'phonetic': '/ˌoʊ keɪ ˈɑːr/',
      'meaningVi': 'mục tiêu & kết quả then chốt',
      'exampleEn': 'Define OKRs quarterly.',
      'exampleVi': 'Xác định OKR theo quý.',
    },
    {
      'word': 'KPI',
      'phonetic': '/ˌkeɪ piː ˈaɪ/',
      'meaningVi': 'chỉ số hiệu suất',
      'exampleEn': 'Align KPIs with strategy.',
      'exampleVi': 'Căn chỉnh KPI với chiến lược.',
    },
    {
      'word': 'alignment',
      'phonetic': '/əˈlaɪnmənt/',
      'meaningVi': 'sự đồng bộ',
      'exampleEn': 'Ensure cross-team alignment.',
      'exampleVi': 'Đảm bảo đồng bộ giữa các đội.',
    },
    {
      'word': 'stakeholder buy-in',
      'phonetic': '/ˈsteɪkˌhoʊldər ˈbaɪ ɪn/',
      'meaningVi': 'sự ủng hộ của bên liên quan',
      'exampleEn': 'Secure stakeholder buy-in.',
      'exampleVi': 'Đạt được sự ủng hộ của các bên liên quan.',
    },
    {
      'word': 'go-to-market',
      'phonetic': '/ˌgoʊ tə ˈmɑːrkɪt/',
      'meaningVi': 'chiến lược thị trường',
      'exampleEn': 'Plan the go-to-market.',
      'exampleVi': 'Lên kế hoạch đưa sản phẩm ra thị trường.',
    },
    {
      'word': 'positioning',
      'phonetic': '/pəˈzɪʃənɪŋ/',
      'meaningVi': 'định vị',
      'exampleEn': 'Refine brand positioning.',
      'exampleVi': 'Tinh chỉnh định vị thương hiệu.',
    },
    {
      'word': 'differentiation',
      'phonetic': '/dɪˌfɛrənʃiˈeɪʃən/',
      'meaningVi': 'khác biệt hóa',
      'exampleEn': 'Create clear differentiation.',
      'exampleVi': 'Tạo khác biệt rõ ràng.',
    },
    {
      'word': 'portfolio',
      'phonetic': '/pɔːrtˈfoʊlioʊ/',
      'meaningVi': 'danh mục',
      'exampleEn': 'Optimize the product portfolio.',
      'exampleVi': 'Tối ưu danh mục sản phẩm.',
    },
    {
      'word': 'synergy',
      'phonetic': '/ˈsɪnərdʒi/',
      'meaningVi': 'hiệu ứng cộng hưởng',
      'exampleEn': 'Seek synergies across units.',
      'exampleVi': 'Tìm kiếm cộng hưởng giữa các đơn vị.',
    },
    {
      'word': 'transformation',
      'phonetic': '/ˌtrænsfərˈmeɪʃən/',
      'meaningVi': 'chuyển đổi',
      'exampleEn': 'Lead a digital transformation.',
      'exampleVi': 'Dẫn dắt chuyển đổi số.',
    },
    {
      'word': 'change management',
      'phonetic': '/tʃeɪndʒ ˈmænɪdʒmənt/',
      'meaningVi': 'quản trị thay đổi',
      'exampleEn': 'Invest in change management.',
      'exampleVi': 'Đầu tư vào quản trị thay đổi.',
    },
    {
      'word': 'adoption',
      'phonetic': '/əˈdɒpʃən/',
      'meaningVi': 'chấp nhận/áp dụng',
      'exampleEn': 'Measure user adoption.',
      'exampleVi': 'Đo lường mức độ chấp nhận của người dùng.',
    },
    {
      'word': 'rollout',
      'phonetic': '/ˈroʊlaʊt/',
      'meaningVi': 'triển khai',
      'exampleEn': 'Plan a phased rollout.',
      'exampleVi': 'Lên kế hoạch triển khai theo giai đoạn.',
    },
    {
      'word': 'resistance',
      'phonetic': '/rɪˈzɪstəns/',
      'meaningVi': 'kháng cự',
      'exampleEn': 'Handle employee resistance.',
      'exampleVi': 'Xử lý sự kháng cự của nhân viên.',
    },
    {
      'word': 'training',
      'phonetic': '/ˈtreɪnɪŋ/',
      'meaningVi': 'đào tạo',
      'exampleEn': 'Schedule training sessions.',
      'exampleVi': 'Lên lịch các buổi đào tạo.',
    },
    {
      'word': 'governance',
      'phonetic': '/ˈɡʌvərnəns/',
      'meaningVi': 'quản trị',
      'exampleEn': 'Strengthen data governance.',
      'exampleVi': 'Tăng cường quản trị dữ liệu.',
    },
    {
      'word': 'playbook',
      'phonetic': '/ˈpleɪbʊk/',
      'meaningVi': 'sổ tay chiến thuật',
      'exampleEn': 'Create a change playbook.',
      'exampleVi': 'Tạo sổ tay triển khai thay đổi.',
    },
    {
      'word': 'business case',
      'phonetic': '/ˈbɪznəs keɪs/',
      'meaningVi': 'luận chứng kinh doanh',
      'exampleEn': 'Write a business case.',
      'exampleVi': 'Viết luận chứng kinh doanh.',
    },
    {
      'word': 'cost-benefit analysis',
      'phonetic': '/kɒst ˈbɛnɪfɪt əˈnæləsɪs/',
      'meaningVi': 'phân tích chi phí-lợi ích',
      'exampleEn': 'Run a cost-benefit analysis.',
      'exampleVi': 'Chạy phân tích chi phí-lợi ích.',
    },
    {
      'word': 'risk appetite',
      'phonetic': '/rɪsk ˈæpɪtaɪt/',
      'meaningVi': 'khẩu vị rủi ro',
      'exampleEn': 'Define your risk appetite.',
      'exampleVi': 'Xác định khẩu vị rủi ro.',
    },
    {
      'word': 'pivot',
      'phonetic': '/ˈpɪvət/',
      'meaningVi': 'đổi hướng',
      'exampleEn': 'We may pivot the strategy.',
      'exampleVi': 'Chúng tôi có thể đổi hướng chiến lược.',
    },
    {
      'word': 'sunset',
      'phonetic': '/ˈsʌnˌsɛt/',
      'meaningVi': 'ngưng (sản phẩm/dịch vụ)',
      'exampleEn': 'Sunset legacy products.',
      'exampleVi': 'Ngưng sản phẩm cũ.',
    },
    {
      'word': 'north star metric',
      'phonetic': '/nɔːrθ stɑːr ˈmɛtrɪk/',
      'meaningVi': 'chỉ số “ngôi sao bắc đẩu”',
      'exampleEn': 'Choose a north star metric.',
      'exampleVi': 'Chọn một chỉ số định hướng.',
    },
    {
      'word': 'operating model',
      'phonetic': '/ˈɒpəreɪtɪŋ ˈmɒdl/',
      'meaningVi': 'mô hình vận hành',
      'exampleEn': 'Redesign the operating model.',
      'exampleVi': 'Thiết kế lại mô hình vận hành.',
    },
    {
      'word': 'stakeholder map',
      'phonetic': '/ˈsteɪkˌhoʊldər mæp/',
      'meaningVi': 'bản đồ bên liên quan',
      'exampleEn': 'Build a stakeholder map.',
      'exampleVi': 'Xây dựng bản đồ bên liên quan.',
    },
    {
      'word': 'communication plan',
      'phonetic': '/kəˌmjuːnɪˈkeɪʃən plæn/',
      'meaningVi': 'kế hoạch truyền thông',
      'exampleEn': 'Share the communication plan.',
      'exampleVi': 'Chia sẻ kế hoạch truyền thông.',
    },
    {
      'word': 'post-mortem',
      'phonetic': '/ˌpoʊst ˈmɔːrtəm/',
      'meaningVi': 'đánh giá sau dự án',
      'exampleEn': 'Hold a post-mortem meeting.',
      'exampleVi': 'Tổ chức họp rút kinh nghiệm.',
    },
  ];

  // =========================================================
  // Vocab 7: Operations & Supply Chain (30 thẻ) — vocab7.pdf
  // =========================================================
  final vocab7 = <Map<String, String>>[
    {
      'word': 'throughput',
      'phonetic': '/ˈθruːˌpʊt/',
      'meaningVi': 'năng lực xử lý',
      'exampleEn': 'Increase plant throughput.',
      'exampleVi': 'Tăng năng lực xử lý của nhà máy.',
    },
    {
      'word': 'bottleneck',
      'phonetic': '/ˈbɒtlˌnɛk/',
      'meaningVi': 'nút thắt cổ chai',
      'exampleEn': 'Fix the packing bottleneck.',
      'exampleVi': 'Sửa nút thắt ở khâu đóng gói.',
    },
    {
      'word': 'lead time',
      'phonetic': '/ˈliːd taɪm/',
      'meaningVi': 'thời gian cung ứng',
      'exampleEn': 'Reduce lead time by 10%.',
      'exampleVi': 'Giảm thời gian cung ứng 10%.',
    },
    {
      'word': 'cycle time',
      'phonetic': '/ˈsaɪkl taɪm/',
      'meaningVi': 'chu kỳ xử lý',
      'exampleEn': 'Measure cycle time per unit.',
      'exampleVi': 'Đo chu kỳ xử lý mỗi đơn vị.',
    },
    {
      'word': 'WIP',
      'phonetic': '/ˌdʌbljuː aɪ ˈpiː/',
      'meaningVi': 'hàng đang làm',
      'exampleEn': 'Lower WIP inventory.',
      'exampleVi': 'Giảm tồn WIP.',
    },
    {
      'word': 'throughput yield',
      'phonetic': '/ˈθruːˌpʊt jiːld/',
      'meaningVi': 'tỷ lệ đầu ra đạt',
      'exampleEn': 'Track throughput yield.',
      'exampleVi': 'Theo dõi tỷ lệ đầu ra đạt.',
    },
    {
      'word': 'utilization',
      'phonetic': '/ˌjuːtɪlaɪˈzeɪʃən/',
      'meaningVi': 'mức sử dụng',
      'exampleEn': 'Machine utilization rose.',
      'exampleVi': 'Mức sử dụng máy tăng.',
    },
    {
      'word': 'capacity',
      'phonetic': '/kəˈpæsɪti/',
      'meaningVi': 'công suất',
      'exampleEn': 'Add capacity next quarter.',
      'exampleVi': 'Tăng công suất quý tới.',
    },
    {
      'word': 'scheduling',
      'phonetic': '/ˈskɛdʒʊlɪŋ/',
      'meaningVi': 'lập lịch',
      'exampleEn': 'Improve production scheduling.',
      'exampleVi': 'Cải thiện lập lịch sản xuất.',
    },
    {
      'word': 'kanban',
      'phonetic': '/ˈkɑːnbæn/',
      'meaningVi': 'kanban',
      'exampleEn': 'Implement a kanban system.',
      'exampleVi': 'Triển khai hệ thống kanban.',
    },
    {
      'word': 'just-in-time',
      'phonetic': '/ˌdʒʌst ɪn ˈtaɪm/',
      'meaningVi': 'đúng lúc (JIT)',
      'exampleEn': 'Adopt just-in-time delivery.',
      'exampleVi': 'Áp dụng giao hàng đúng lúc.',
    },
    {
      'word': 'safety stock',
      'phonetic': '/ˈseɪfti stɒk/',
      'meaningVi': 'tồn kho an toàn',
      'exampleEn': 'Increase safety stock.',
      'exampleVi': 'Tăng tồn kho an toàn.',
    },
    {
      'word': 'MRP',
      'phonetic': '/ˌɛm ɑːr ˈpiː/',
      'meaningVi': 'kế hoạch nhu cầu vật tư',
      'exampleEn': 'Run MRP weekly.',
      'exampleVi': 'Chạy MRP hàng tuần.',
    },
    {
      'word': 'batch size',
      'phonetic': '/bætʃ saɪz/',
      'meaningVi': 'cỡ lô',
      'exampleEn': 'Optimize batch size.',
      'exampleVi': 'Tối ưu cỡ lô.',
    },
    {
      'word': 'order fulfillment',
      'phonetic': '/ˈɔːrdər fʊlˈfɪlmənt/',
      'meaningVi': 'xử lý đơn hàng',
      'exampleEn': 'Speed up order fulfillment.',
      'exampleVi': 'Tăng tốc xử lý đơn hàng.',
    },
    {
      'word': 'cross-docking',
      'phonetic': '/ˌkrɒs ˈdɒkɪŋ/',
      'meaningVi': 'trung chuyển (cross-dock)',
      'exampleEn': 'Use cross-docking for fast movers.',
      'exampleVi': 'Dùng cross-docking cho hàng chạy nhanh.',
    },
    {
      'word': '3PL',
      'phonetic': '/ˌθriː piː ˈɛl/',
      'meaningVi': 'đối tác logistics thứ ba',
      'exampleEn': 'Contract a 3PL provider.',
      'exampleVi': 'Ký với nhà cung cấp 3PL.',
    },
    {
      'word': 'SKU rationalization',
      'phonetic': '/ˌɛs keɪ ˈjuː ˌræʃənəlaɪˈzeɪʃən/',
      'meaningVi': 'tinh gọn danh mục SKU',
      'exampleEn': 'Do SKU rationalization.',
      'exampleVi': 'Tinh gọn danh mục SKU.',
    },
    {
      'word': 'S&OP',
      'phonetic': '/ˌɛs ən oʊ ˈpiː/',
      'meaningVi': 'hoạch định bán hàng & vận hành',
      'exampleEn': 'Hold monthly S&OP meetings.',
      'exampleVi': 'Tổ chức họp S&OP hàng tháng.',
    },
    {
      'word': 'forecast accuracy',
      'phonetic': '/ˈfɔːrkæst ˈækjərəsi/',
      'meaningVi': 'độ chính xác dự báo',
      'exampleEn': 'Improve forecast accuracy.',
      'exampleVi': 'Cải thiện độ chính xác dự báo.',
    },
    {
      'word': 'demand planning',
      'phonetic': '/dɪˈmɑːnd ˈplænɪŋ/',
      'meaningVi': 'hoạch định nhu cầu',
      'exampleEn': 'Strengthen demand planning.',
      'exampleVi': 'Tăng cường hoạch định nhu cầu.',
    },
    {
      'word': 'supply risk',
      'phonetic': '/səˈplaɪ rɪsk/',
      'meaningVi': 'rủi ro cung ứng',
      'exampleEn': 'Monitor supply risks.',
      'exampleVi': 'Theo dõi rủi ro cung ứng.',
    },
    {
      'word': 'single-source',
      'phonetic': '/ˈsɪŋɡl sɔːrs/',
      'meaningVi': 'đơn nguồn',
      'exampleEn': 'Avoid single-source suppliers.',
      'exampleVi': 'Tránh nhà cung cấp đơn nguồn.',
    },
    {
      'word': 'dual-source',
      'phonetic': '/ˈdjuːəl sɔːrs/',
      'meaningVi': 'hai nguồn',
      'exampleEn': 'Dual-source critical parts.',
      'exampleVi': 'Mua hai nguồn cho linh kiện quan trọng.',
    },
    {
      'word': 'backorder',
      'phonetic': '/ˈbækˌɔːrdər/',
      'meaningVi': 'đơn chờ hàng',
      'exampleEn': 'Reduce backorders in Q3.',
      'exampleVi': 'Giảm đơn chờ hàng trong quý 3.',
    },
    {
      'word': 'fill rate',
      'phonetic': '/fɪl reɪt/',
      'meaningVi': 'tỷ lệ đáp ứng đơn',
      'exampleEn': 'Increase the fill rate.',
      'exampleVi': 'Tăng tỷ lệ đáp ứng đơn.',
    },
    {
      'word': 'OTIF',
      'phonetic': '/ˌoʊ tiː aɪ ˈɛf/',
      'meaningVi': 'đúng hạn đúng đủ',
      'exampleEn': 'Track OTIF monthly.',
      'exampleVi': 'Theo dõi OTIF hàng tháng.',
    },
    {
      'word': 'returns processing',
      'phonetic': '/rɪˈtɜːrnz ˈprɒsɛsɪŋ/',
      'meaningVi': 'xử lý hàng trả',
      'exampleEn': 'Improve returns processing.',
      'exampleVi': 'Cải thiện xử lý hàng trả.',
    },
    {
      'word': 'reverse logistics',
      'phonetic': '/rɪˈvɜːrs loʊˈdʒɪstɪks/',
      'meaningVi': 'hậu cần ngược',
      'exampleEn': 'Set up reverse logistics.',
      'exampleVi': 'Thiết lập hậu cần ngược.',
    },
    {
      'word': 'continuous flow',
      'phonetic': '/kənˈtɪnjʊəs floʊ/',
      'meaningVi': 'dòng chảy liên tục',
      'exampleEn': 'Design for continuous flow.',
      'exampleVi': 'Thiết kế cho dòng chảy liên tục.',
    },
  ];

  // =========================================================
  // Vocab 8: Risk & Compliance (30 thẻ) — vocab8.pdf
  // =========================================================
  final vocab8 = <Map<String, String>>[
    {
      'word': 'mitigate',
      'phonetic': '/ˈmɪtɪɡeɪt/',
      'meaningVi': 'giảm thiểu',
      'exampleEn': 'Mitigate supply risks.',
      'exampleVi': 'Giảm thiểu rủi ro cung ứng.',
    },
    {
      'word': 'risk assessment',
      'phonetic': '/rɪsk əˈsɛsmənt/',
      'meaningVi': 'đánh giá rủi ro',
      'exampleEn': 'Conduct a risk assessment.',
      'exampleVi': 'Tiến hành đánh giá rủi ro.',
    },
    {
      'word': 'risk register',
      'phonetic': '/rɪsk ˈrɛdʒɪstər/',
      'meaningVi': 'sổ đăng ký rủi ro',
      'exampleEn': 'Update the risk register.',
      'exampleVi': 'Cập nhật sổ rủi ro.',
    },
    {
      'word': 'likelihood',
      'phonetic': '/ˈlaɪkliˌhʊd/',
      'meaningVi': 'khả năng xảy ra',
      'exampleEn': 'Estimate the likelihood.',
      'exampleVi': 'Ước tính khả năng xảy ra.',
    },
    {
      'word': 'impact',
      'phonetic': '/ˈɪmpækt/',
      'meaningVi': 'mức độ ảnh hưởng',
      'exampleEn': 'Rate the impact high.',
      'exampleVi': 'Đánh giá mức ảnh hưởng cao.',
    },
    {
      'word': 'controls',
      'phonetic': '/kənˈtroʊlz/',
      'meaningVi': 'biện pháp kiểm soát',
      'exampleEn': 'Strengthen internal controls.',
      'exampleVi': 'Tăng cường kiểm soát nội bộ.',
    },
    {
      'word': 'governance',
      'phonetic': '/ˈɡʌvərnəns/',
      'meaningVi': 'quản trị',
      'exampleEn': 'Improve governance practices.',
      'exampleVi': 'Cải thiện thực hành quản trị.',
    },
    {
      'word': 'policy',
      'phonetic': '/ˈpɒlɪsi/',
      'meaningVi': 'chính sách',
      'exampleEn': 'Update the compliance policy.',
      'exampleVi': 'Cập nhật chính sách tuân thủ.',
    },
    {
      'word': 'procedure',
      'phonetic': '/prəˈsiːdʒər/',
      'meaningVi': 'quy trình',
      'exampleEn': 'Document all procedures.',
      'exampleVi': 'Ghi chép mọi quy trình.',
    },
    {
      'word': 'compliance audit',
      'phonetic': '/kəmˈplaɪəns ˈɔːdɪt/',
      'meaningVi': 'đánh giá tuân thủ',
      'exampleEn': 'Plan a compliance audit.',
      'exampleVi': 'Lên lịch đánh giá tuân thủ.',
    },
    {
      'word': 'due diligence',
      'phonetic': '/ˌdjuː ˈdɪlɪdʒəns/',
      'meaningVi': 'thẩm tra (đầu tư/mua bán)',
      'exampleEn': 'Perform due diligence.',
      'exampleVi': 'Thực hiện thẩm tra.',
    },
    {
      'word': 'regulation',
      'phonetic': '/ˌrɛɡjʊˈleɪʃən/',
      'meaningVi': 'quy định',
      'exampleEn': 'New regulations were issued.',
      'exampleVi': 'Đã ban hành quy định mới.',
    },
    {
      'word': 'sanction',
      'phonetic': '/ˈsæŋkʃən/',
      'meaningVi': 'chế tài',
      'exampleEn': 'Sanctions may apply.',
      'exampleVi': 'Có thể áp dụng chế tài.',
    },
    {
      'word': 'whistleblower',
      'phonetic': '/ˈwɪsəlˌbloʊər/',
      'meaningVi': 'người tố giác',
      'exampleEn': 'Protect whistleblowers.',
      'exampleVi': 'Bảo vệ người tố giác.',
    },
    {
      'word': 'fraud',
      'phonetic': '/frɔːd/',
      'meaningVi': 'gian lận',
      'exampleEn': 'Report suspected fraud.',
      'exampleVi': 'Báo cáo nghi ngờ gian lận.',
    },
    {
      'word': 'bribery',
      'phonetic': '/ˈbraɪbəri/',
      'meaningVi': 'hối lộ',
      'exampleEn': 'Anti-bribery rules are strict.',
      'exampleVi': 'Quy định chống hối lộ nghiêm ngặt.',
    },
    {
      'word': 'conflict of interest',
      'phonetic': '/ˌkɒnflɪkt əv ˈɪntrəst/',
      'meaningVi': 'xung đột lợi ích',
      'exampleEn': 'Declare conflicts of interest.',
      'exampleVi': 'Khai báo xung đột lợi ích.',
    },
    {
      'word': 'code of conduct',
      'phonetic': '/koʊd əv ˈkɒndʌkt/',
      'meaningVi': 'quy tắc ứng xử',
      'exampleEn': 'Follow the code of conduct.',
      'exampleVi': 'Tuân theo quy tắc ứng xử.',
    },
    {
      'word': 'anti-money laundering',
      'phonetic': '/ˌænti ˈmʌni ˈlɔːndərɪŋ/',
      'meaningVi': 'chống rửa tiền (AML)',
      'exampleEn': 'Implement AML checks.',
      'exampleVi': 'Triển khai kiểm tra AML.',
    },
    {
      'word': 'KYC',
      'phonetic': '/ˌkeɪ waɪ ˈsiː/',
      'meaningVi': 'xác minh khách hàng',
      'exampleEn': 'Complete KYC procedures.',
      'exampleVi': 'Hoàn tất thủ tục KYC.',
    },
    {
      'word': 'data privacy',
      'phonetic': '/ˈdeɪtə ˈpraɪvəsi/',
      'meaningVi': 'quyền riêng tư dữ liệu',
      'exampleEn': 'Ensure data privacy.',
      'exampleVi': 'Đảm bảo quyền riêng tư dữ liệu.',
    },
    {
      'word': 'GDPR',
      'phonetic': '/ˌdʒiː diː piː ˈɑːr/',
      'meaningVi': 'Quy định bảo vệ dữ liệu EU',
      'exampleEn': 'Comply with GDPR.',
      'exampleVi': 'Tuân thủ GDPR.',
    },
    {
      'word': 'incident',
      'phonetic': '/ˈɪnsɪdənt/',
      'meaningVi': 'sự cố',
      'exampleEn': 'Log the incident immediately.',
      'exampleVi': 'Ghi nhận sự cố ngay.',
    },
    {
      'word': 'remediation',
      'phonetic': '/rɪˌmiːdiˈeɪʃən/',
      'meaningVi': 'khắc phục',
      'exampleEn': 'Start remediation steps.',
      'exampleVi': 'Bắt đầu bước khắc phục.',
    },
    {
      'word': 'business continuity',
      'phonetic': '/ˈbɪznəs kɒn tɪˈnjuːɪti/',
      'meaningVi': 'liên tục kinh doanh',
      'exampleEn': 'Test the continuity plan.',
      'exampleVi': 'Kiểm thử kế hoạch liên tục kinh doanh.',
    },
    {
      'word': 'contingency plan',
      'phonetic': '/kənˈtɪndʒənsi plæn/',
      'meaningVi': 'kế hoạch dự phòng',
      'exampleEn': 'Maintain a contingency plan.',
      'exampleVi': 'Duy trì kế hoạch dự phòng.',
    },
    {
      'word': 'risk tolerance',
      'phonetic': '/rɪsk ˈtɒlərəns/',
      'meaningVi': 'ngưỡng chịu rủi ro',
      'exampleEn': 'Set risk tolerance levels.',
      'exampleVi': 'Đặt mức ngưỡng rủi ro.',
    },
    {
      'word': 'escalation',
      'phonetic': '/ˌɛskəˈleɪʃən/',
      'meaningVi': 'leo thang xử lý',
      'exampleEn': 'Define escalation procedures.',
      'exampleVi': 'Định nghĩa quy trình leo thang.',
    },
    {
      'word': 'attestation',
      'phonetic': '/ˌætɛsˈteɪʃən/',
      'meaningVi': 'xác nhận chứng thực',
      'exampleEn': 'Annual attestation is required.',
      'exampleVi': 'Yêu cầu xác nhận hằng năm.',
    },
    {
      'word': 'regulatory filing',
      'phonetic': '/ˈrɛɡjʊlətəri ˈfaɪlɪŋ/',
      'meaningVi': 'hồ sơ nộp cơ quan quản lý',
      'exampleEn': 'Submit regulatory filings.',
      'exampleVi': 'Nộp hồ sơ cho cơ quan quản lý.',
    },
  ];

  // =========================================================
  // Vocab 9: Advanced Marketing & ROI (30 thẻ) — vocab9.pdf
  // =========================================================
  final vocab9 = <Map<String, String>>[
    {
      'word': 'segmentation',
      'phonetic': '/ˌsɛɡmɛnˈteɪʃən/',
      'meaningVi': 'phân khúc',
      'exampleEn': 'Refine customer segmentation.',
      'exampleVi': 'Tinh chỉnh phân khúc khách hàng.',
    },
    {
      'word': 'positioning',
      'phonetic': '/pəˈzɪʃənɪŋ/',
      'meaningVi': 'định vị',
      'exampleEn': 'Our positioning is premium.',
      'exampleVi': 'Định vị của chúng tôi là cao cấp.',
    },
    {
      'word': 'brand equity',
      'phonetic': '/brænd ˈɛkwɪti/',
      'meaningVi': 'giá trị thương hiệu',
      'exampleEn': 'Build brand equity over time.',
      'exampleVi': 'Xây dựng giá trị thương hiệu theo thời gian.',
    },
    {
      'word': 'value proposition',
      'phonetic': '/ˈvæljuː ˌprɒpəˈzɪʃən/',
      'meaningVi': 'giá trị đề xuất',
      'exampleEn': 'Clarify the value proposition.',
      'exampleVi': 'Làm rõ giá trị đề xuất.',
    },
    {
      'word': 'persona',
      'phonetic': '/pərˈsoʊnə/',
      'meaningVi': 'chân dung khách hàng',
      'exampleEn': 'Create buyer personas.',
      'exampleVi': 'Tạo chân dung người mua.',
    },
    {
      'word': 'attribution',
      'phonetic': '/ˌætrɪˈbjuːʃən/',
      'meaningVi': 'quy gán hiệu quả',
      'exampleEn': 'Use multi-touch attribution.',
      'exampleVi': 'Dùng quy gán đa điểm chạm.',
    },
    {
      'word': 'LTV',
      'phonetic': '/ˌel tiː ˈviː/',
      'meaningVi': 'giá trị vòng đời khách hàng',
      'exampleEn': 'Increase LTV by 15%.',
      'exampleVi': 'Tăng LTV thêm 15%.',
    },
    {
      'word': 'CAC',
      'phonetic': '/ˌsiː eɪ ˈsiː/',
      'meaningVi': 'chi phí thu hút khách',
      'exampleEn': 'Reduce CAC in Q2.',
      'exampleVi': 'Giảm CAC trong quý 2.',
    },
    {
      'word': 'churn rate',
      'phonetic': '/tʃɜːrn reɪt/',
      'meaningVi': 'tỷ lệ rời bỏ',
      'exampleEn': 'Lower the churn rate.',
      'exampleVi': 'Giảm tỷ lệ rời bỏ.',
    },
    {
      'word': 'A/B testing',
      'phonetic': '/ˌeɪ ˈbiː ˈtɛstɪŋ/',
      'meaningVi': 'thử nghiệm A/B',
      'exampleEn': 'Run continuous A/B testing.',
      'exampleVi': 'Chạy A/B liên tục.',
    },
    {
      'word': 'statistical significance',
      'phonetic': '/stəˈtɪstɪkəl sɪɡˈnɪfɪkəns/',
      'meaningVi': 'ý nghĩa thống kê',
      'exampleEn': 'Check statistical significance.',
      'exampleVi': 'Kiểm tra ý nghĩa thống kê.',
    },
    {
      'word': 'confidence interval',
      'phonetic': '/ˈkɒnfɪdəns ˈɪntərvəl/',
      'meaningVi': 'khoảng tin cậy',
      'exampleEn': 'Report the confidence interval.',
      'exampleVi': 'Báo cáo khoảng tin cậy.',
    },
    {
      'word': 'funnel',
      'phonetic': '/ˈfʌnl/',
      'meaningVi': 'phễu',
      'exampleEn': 'Optimize the conversion funnel.',
      'exampleVi': 'Tối ưu phễu chuyển đổi.',
    },
    {
      'word': 'top-of-funnel',
      'phonetic': '/tɒp əv ˈfʌnl/',
      'meaningVi': 'đầu phễu',
      'exampleEn': 'Boost top-of-funnel traffic.',
      'exampleVi': 'Tăng lưu lượng đầu phễu.',
    },
    {
      'word': 'bottom-of-funnel',
      'phonetic': '/ˈbɒtəm əv ˈfʌnl/',
      'meaningVi': 'cuối phễu',
      'exampleEn': 'Improve bottom-of-funnel CR.',
      'exampleVi': 'Cải thiện tỷ lệ chuyển đổi cuối phễu.',
    },
    {
      'word': 'retargeting',
      'phonetic': '/riːˈtɑːɡɪtɪŋ/',
      'meaningVi': 'tiếp thị bám đuổi',
      'exampleEn': 'Launch retargeting ads.',
      'exampleVi': 'Chạy quảng cáo bám đuổi.',
    },
    {
      'word': 'lookalike audience',
      'phonetic': '/ˈlʊkəlaɪk ˈɔːdiəns/',
      'meaningVi': 'tệp tương tự',
      'exampleEn': 'Build a lookalike audience.',
      'exampleVi': 'Tạo tệp tương tự.',
    },
    {
      'word': 'marketing mix',
      'phonetic': '/ˈmɑːrkɪtɪŋ mɪks/',
      'meaningVi': 'phối thức marketing',
      'exampleEn': 'Adjust the marketing mix.',
      'exampleVi': 'Điều chỉnh phối thức marketing.',
    },
    {
      'word': 'media spend',
      'phonetic': '/ˈmiːdiə spɛnd/',
      'meaningVi': 'ngân sách truyền thông',
      'exampleEn': 'Optimize media spend.',
      'exampleVi': 'Tối ưu ngân sách truyền thông.',
    },
    {
      'word': 'ROI',
      'phonetic': '/ˌɑːr oʊ ˈaɪ/',
      'meaningVi': 'lợi tức đầu tư',
      'exampleEn': 'Maximize campaign ROI.',
      'exampleVi': 'Tối đa hóa ROI chiến dịch.',
    },
    {
      'word': 'ROAS',
      'phonetic': '/ˌɑːr oʊ eɪ ˈɛs/',
      'meaningVi': 'lợi tức chi cho quảng cáo',
      'exampleEn': 'Target a 4x ROAS.',
      'exampleVi': 'Mục tiêu ROAS gấp 4.',
    },
    {
      'word': 'CPL',
      'phonetic': '/ˌsiː piː ˈɛl/',
      'meaningVi': 'chi phí/lead',
      'exampleEn': 'Lower CPL by automation.',
      'exampleVi': 'Giảm CPL bằng tự động hóa.',
    },
    {
      'word': 'CPM',
      'phonetic': '/ˌsiː piː ˈɛm/',
      'meaningVi': 'chi phí/1000 hiển thị',
      'exampleEn': 'Negotiate lower CPM.',
      'exampleVi': 'Đàm phán CPM thấp hơn.',
    },
    {
      'word': 'CTR',
      'phonetic': '/ˌsiː tiː ˈɑːr/',
      'meaningVi': 'tỷ lệ nhấp',
      'exampleEn': 'Increase CTR with new creatives.',
      'exampleVi': 'Tăng CTR với sáng tạo mới.',
    },
    {
      'word': 'conversion lift',
      'phonetic': '/kənˈvɜːrʒn lɪft/',
      'meaningVi': 'mức tăng chuyển đổi',
      'exampleEn': 'Measure conversion lift.',
      'exampleVi': 'Đo lường mức tăng chuyển đổi.',
    },
    {
      'word': 'incrementality',
      'phonetic': '/ˌɪnkrɪmɛnˈtæləti/',
      'meaningVi': 'tính gia tăng',
      'exampleEn': 'Test incrementality.',
      'exampleVi': 'Kiểm thử tính gia tăng.',
    },
    {
      'word': 'cohort analysis',
      'phonetic': '/ˈkoʊhɔːrt əˈnæləsɪs/',
      'meaningVi': 'phân tích theo nhóm khách',
      'exampleEn': 'Do a cohort analysis.',
      'exampleVi': 'Thực hiện phân tích cohort.',
    },
    {
      'word': 'brand lift',
      'phonetic': '/brænd lɪft/',
      'meaningVi': 'mức nâng nhận biết',
      'exampleEn': 'Track brand lift.',
      'exampleVi': 'Theo dõi brand lift.',
    },
    {
      'word': 'market share',
      'phonetic': '/ˈmɑːrkɪt ʃeər/',
      'meaningVi': 'thị phần',
      'exampleEn': 'Gain market share.',
      'exampleVi': 'Gia tăng thị phần.',
    },
    {
      'word': 'pricing elasticity',
      'phonetic': '/ˈpraɪsɪŋ iːˌlæˈstɪsɪti/',
      'meaningVi': 'độ co giãn giá',
      'exampleEn': 'Model pricing elasticity.',
      'exampleVi': 'Mô hình hóa độ co giãn giá.',
    },
  ];

  // =========================================================
  // Vocab 10: Formal Correspondence Pro+ (30 thẻ) — vocab10.pdf
  // =========================================================
  final vocab10 = <Map<String, String>>[
    {
      'word': 'hereby',
      'phonetic': '/ˈhɪəbaɪ/',
      'meaningVi': 'bằng văn bản này',
      'exampleEn': 'We hereby confirm receipt.',
      'exampleVi': 'Chúng tôi bằng văn bản này xác nhận đã nhận.',
    },
    {
      'word': 'herewith',
      'phonetic': '/ˌhɪəˈwɪð/',
      'meaningVi': 'kèm theo đây',
      'exampleEn': 'Please find herewith the invoice.',
      'exampleVi': 'Vui lòng xem kèm theo đây hóa đơn.',
    },
    {
      'word': 'thereof',
      'phonetic': '/ðeərˈɒv/',
      'meaningVi': 'của cái đó',
      'exampleEn': 'Terms and conditions thereof apply.',
      'exampleVi': 'Áp dụng các điều khoản của tài liệu đó.',
    },
    {
      'word': 'therein',
      'phonetic': '/ˌðeərˈɪn/',
      'meaningVi': 'trong đó',
      'exampleEn': 'As specified therein.',
      'exampleVi': 'Như được nêu trong đó.',
    },
    {
      'word': 'hereto',
      'phonetic': '/ˌhɪəˈtuː/',
      'meaningVi': 'đính kèm vào văn kiện này',
      'exampleEn': 'See Annex A hereto.',
      'exampleVi': 'Xem Phụ lục A đính kèm văn kiện này.',
    },
    {
      'word': 'aforementioned',
      'phonetic': '/əˌfɔːˈmɛnʃənd/',
      'meaningVi': 'nêu trên',
      'exampleEn': 'The aforementioned document is valid.',
      'exampleVi': 'Tài liệu nêu trên hợp lệ.',
    },
    {
      'word': 'notwithstanding',
      'phonetic': '/ˌnɒtwɪðˈstændɪŋ/',
      'meaningVi': 'mặc dù',
      'exampleEn': 'Notwithstanding the delay, we proceed.',
      'exampleVi': 'Mặc dù chậm trễ, chúng tôi vẫn tiến hành.',
    },
    {
      'word': 'pursuant to',
      'phonetic': '/pəˈsjuːənt tuː/',
      'meaningVi': 'theo như',
      'exampleEn': 'Pursuant to your request, we enclose…',
      'exampleVi': 'Theo yêu cầu của bạn, chúng tôi đính kèm…',
    },
    {
      'word': 'enclose',
      'phonetic': '/ɪnˈkloʊz/',
      'meaningVi': 'đính kèm',
      'exampleEn': 'We enclose the signed form.',
      'exampleVi': 'Chúng tôi đính kèm mẫu đã ký.',
    },
    {
      'word': 'acknowledge',
      'phonetic': '/əkˈnɒlɪdʒ/',
      'meaningVi': 'xác nhận',
      'exampleEn': 'We acknowledge your letter.',
      'exampleVi': 'Chúng tôi xác nhận thư của bạn.',
    },
    {
      'word': 'endorse',
      'phonetic': '/ɪnˈdɔːs/',
      'meaningVi': 'chứng thực/tán thành',
      'exampleEn': 'The board endorsed the plan.',
      'exampleVi': 'HĐQT đã tán thành kế hoạch.',
    },
    {
      'word': 'consent',
      'phonetic': '/kənˈsɛnt/',
      'meaningVi': 'đồng ý/chấp thuận',
      'exampleEn': 'Please provide written consent.',
      'exampleVi': 'Vui lòng cung cấp chấp thuận bằng văn bản.',
    },
    {
      'word': 'undertake',
      'phonetic': '/ˌʌndəˈteɪk/',
      'meaningVi': 'cam kết thực hiện',
      'exampleEn': 'We undertake to deliver on time.',
      'exampleVi': 'Chúng tôi cam kết giao đúng hạn.',
    },
    {
      'word': 'nonetheless',
      'phonetic': '/ˌnʌnðəˈlɛs/',
      'meaningVi': 'tuy nhiên',
      'exampleEn': 'Nonetheless, we remain supportive.',
      'exampleVi': 'Tuy nhiên, chúng tôi vẫn ủng hộ.',
    },
    {
      'word': 'whereas',
      'phonetic': '/ˌwɛərˈæz/',
      'meaningVi': 'xét rằng',
      'exampleEn': 'Whereas the parties agree as follows…',
      'exampleVi': 'Xét rằng các bên đồng ý như sau…',
    },
    {
      'word': 'hereinafter',
      'phonetic': '/ˌhɪərɪˈnɑːftər/',
      'meaningVi': 'sau đây',
      'exampleEn': 'The vendor, hereinafter “Supplier”.',
      'exampleVi': 'Nhà bán, sau đây gọi là “Nhà cung cấp”.',
    },
    {
      'word': 'forthcoming',
      'phonetic': '/ˌfɔːrθˈkʌmɪŋ/',
      'meaningVi': 'sắp tới',
      'exampleEn': 'We await your forthcoming response.',
      'exampleVi': 'Chúng tôi chờ phản hồi sắp tới.',
    },
    {
      'word': 'expedite',
      'phonetic': '/ˈɛkspɪdaɪt/',
      'meaningVi': 'đẩy nhanh',
      'exampleEn': 'Please expedite the shipment.',
      'exampleVi': 'Vui lòng đẩy nhanh lô hàng.',
    },
    {
      'word': 'defer',
      'phonetic': '/dɪˈfɜːr/',
      'meaningVi': 'hoãn lại',
      'exampleEn': 'We will defer the meeting.',
      'exampleVi': 'Chúng tôi sẽ hoãn cuộc họp.',
    },
    {
      'word': 'rectify',
      'phonetic': '/ˈrɛktɪfaɪ/',
      'meaningVi': 'sửa sai',
      'exampleEn': 'We will rectify the error.',
      'exampleVi': 'Chúng tôi sẽ sửa lỗi.',
    },
    {
      'word': 'redress',
      'phonetic': '/rɪˈdrɛs/',
      'meaningVi': 'khắc phục/đền bù',
      'exampleEn': 'We seek redress for losses.',
      'exampleVi': 'Chúng tôi yêu cầu đền bù thiệt hại.',
    },
    {
      'word': 'pertinent',
      'phonetic': '/ˈpɜːtɪnənt/',
      'meaningVi': 'liên quan',
      'exampleEn': 'Provide all pertinent details.',
      'exampleVi': 'Cung cấp mọi chi tiết liên quan.',
    },
    {
      'word': 'aforementioned parties',
      'phonetic': '/əˌfɔːˈmɛnʃənd ˈpɑːrtiz/',
      'meaningVi': 'các bên nêu trên',
      'exampleEn': 'The aforementioned parties consented.',
      'exampleVi': 'Các bên nêu trên đã đồng ý.',
    },
    {
      'word': 'overdue',
      'phonetic': '/ˌoʊvərˈduː/',
      'meaningVi': 'quá hạn',
      'exampleEn': 'Your payment is overdue.',
      'exampleVi': 'Thanh toán của bạn đã quá hạn.',
    },
    {
      'word': 'remit',
      'phonetic': '/rɪˈmɪt/',
      'meaningVi': 'chuyển tiền',
      'exampleEn': 'Please remit the balance.',
      'exampleVi': 'Vui lòng chuyển phần tiền còn lại.',
    },
    {
      'word': 'enquiry',
      'phonetic': '/ɪnˈkwaɪəri/',
      'meaningVi': 'thư hỏi thông tin',
      'exampleEn': 'We respond to your enquiry.',
      'exampleVi': 'Chúng tôi phản hồi thư hỏi của bạn.',
    },
    {
      'word': 'courtesy',
      'phonetic': '/ˈkɜːrtəsi/',
      'meaningVi': 'thiện chí/nhã ý',
      'exampleEn': 'As a courtesy, we extended the term.',
      'exampleVi': 'Như một nhã ý, chúng tôi gia hạn thời hạn.',
    },
    {
      'word': 'grievance',
      'phonetic': '/ˈɡriːvəns/',
      'meaningVi': 'khiếu nại',
      'exampleEn': 'File a formal grievance.',
      'exampleVi': 'Nộp khiếu nại chính thức.',
    },
    {
      'word': 'annex',
      'phonetic': '/ˈænɛks/',
      'meaningVi': 'phụ lục; đính kèm',
      'exampleEn': 'See the annex for details.',
      'exampleVi': 'Xem phụ lục để biết chi tiết.',
    },
    {
      'word': 'convey',
      'phonetic': '/kənˈveɪ/',
      'meaningVi': 'truyền đạt',
      'exampleEn': 'Kindly convey our thanks.',
      'exampleVi': 'Vui lòng truyền đạt lời cảm ơn của chúng tôi.',
    },
  ];

  // === Ghi các topic vào Firestore
  await _seedTopic(
    topicId: 'vocab1',
    topicName: 'Bài 1: Reports & Data Insights',
    cards: vocab1,
  );
  await _seedTopic(
    topicId: 'vocab2',
    topicName: 'Bài 2: Budgeting & Forecasting',
    cards: vocab2,
  );
  await _seedTopic(
    topicId: 'vocab3',
    topicName: 'Bài 3: Contracts & Legal Terms',
    cards: vocab3,
  );
  await _seedTopic(
    topicId: 'vocab4',
    topicName: 'Bài 4: Procurement Advanced',
    cards: vocab4,
  );
  await _seedTopic(
    topicId: 'vocab5',
    topicName: 'Bài 5: Quality & Audits',
    cards: vocab5,
  );
  await _seedTopic(
    topicId: 'vocab6',
    topicName: 'Bài 6: Corporate Strategy & Change',
    cards: vocab6,
  );
  await _seedTopic(
    topicId: 'vocab7',
    topicName: 'Bài 7: Operations & Supply Chain',
    cards: vocab7,
  );
  await _seedTopic(
    topicId: 'vocab8',
    topicName: 'Bài 8: Risk & Compliance',
    cards: vocab8,
  );
  await _seedTopic(
    topicId: 'vocab9',
    topicName: 'Bài 9: Advanced Marketing & ROI',
    cards: vocab9,
  );
  await _seedTopic(
    topicId: 'vocab10',
    topicName: 'Bài 10: Formal Correspondence Pro+',
    cards: vocab10,
  );
}
